### PR TITLE
Use SIGWINCH to print thread backtraces

### PR DESCRIPTION
**Pull request by stanhu**
### Description

https://github.com/puma/puma/pull/1320 added support for using SIGINFO,
but this is only available on BSD-based systems. SIGWINCH is on Linux.

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` the pull request title.
- [x] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by nateberkopec** [comment]
SIGPROF is already used pretty widely in profilers, e.g. [stackprof](https://github.com/tmm1/stackprof/search?q=SIGPROF&type=).

I'm not sure we can use that signal.

**Comment by nateberkopec** [comment]
Just looking at the BSD signal list, maybe SIGVTALRM or SIGWINCH? [I'd like to know what people get for the `Signal.list` on other platforms, btw.](https://twitter.com/nateberkopec/status/1242344897782267904)

**Comment by nateberkopec** [comment]
NVM, Ruby uses SIGVTALRM internally. SIGWINCH however probably won't interfere with anyone's existing handlers in a webapp.

**Comment by stanhu** [comment]
On Linux, I get

```
{"EXIT"=>0, "HUP"=>1, "INT"=>2, "QUIT"=>3, "ILL"=>4, "TRAP"=>5, "ABRT"=>6, "IOT"=>6, "FPE"=>8, "KILL"=>9, "BUS"=>7, "SEGV"=>11, "SYS"=>31, "PIPE"=>13, "ALRM"=>14, "TERM"=>15, "URG"=>23, "STOP"=>19, "TSTP"=>20, "CONT"=>18, "CHLD"=>17, "CLD"=>17, "TTIN"=>21, "TTOU"=>22, "IO"=>29, "XCPU"=>24, "XFSZ"=>25, "VTALRM"=>26, "PROF"=>27, "WINCH"=>28, "USR1"=>10, "USR2"=>12, "PWR"=>30, "POLL"=>29}
```

**Comment by nateberkopec** [comment]
Sounds like SIGWINCH is probably the best option then, yeh?

**Comment by stanhu** [comment]
Yes, thanks.

I've also wondered why attaching `gdb` to Puma and calling `call rb_backtrace()` doesn't work like it does in Unicorn and Sidekiq. Is th

**Comment by nateberkopec** [comment]
> I've also wondered why attaching gdb to Puma and calling call rb_backtrace() doesn't work like it does in Unicorn and Sidekiq.

Can you open a new issue?

**Comment by nateberkopec** [comment]
I think we're going to have to revert. SIGWINCH gets sent all the time when changing window sizes and so this makes terminal output kind of unusable locally.

I'm not sure any other signal would work.

**Comment by stanhu** [comment]
Ok. Is it possible to use `TTIN` as Sidekiq does, and then make it clear that signal does two different things, depending on whether it's sent to the worker process or the cluster worker?

**Comment by nateberkopec** [comment]
Maybe. Do we listen for TTIN in child workers at all right now?

**Comment by stanhu** [comment]
@nateberkopec Not at the moment. I think I got it to work. It would be a breaking change for anyone issuing `TTIN` on the cluster workers, though.

**Comment by eregon** [comment]
FWIW, TruffleRuby prints all thread backtraces on `SIGALRM`.
Maybe we should ask for this feature in MRI instead of adding it here?

**Comment by dentarg** [comment]
@eregon Nate commented "Ruby uses SIGVTALRM internally" above, but I'm not sure for what (from a [really quick look](https://github.com/ruby/ruby/search?q=ALRM&unscoped_q=ALRM))

**Comment by eregon** [comment]
SIGALRM is different than SIGVTALRM (which is reserved in MRI & TruffleRuby).

See https://github.com/ruby/spec/blob/ebdf0d1b06b39374a85baaae53771449ab1fe3d7/core/signal/trap_spec.rb#L118-L133 for the list of reserved signals for each Ruby implementation.

**Comment by dentarg** [comment]
Thanks for clarifying that @eregon 

(I should have search for [`SIGVTALRM`](https://github.com/ruby/ruby/search?q=SIGVTALRM&unscoped_q=SIGVTALRM) not just `ALRM`, the GitHub search doesn't seem to surface partial hits)

**Pull request merged**
