### PR TITLE
Document that `DefaultRackup` et al. was removed [ci skip]

### LINKED ISSUE #2989: Uninitialized constant Puma::DSL::DefaultRackup
**Describe the bug**

I tried upgrading one of my production applications, but got the following error:

<details>
  <summary>bundle exec rails server</summary>
  
```bash
config/puma.rb:7:in `_load_from': uninitialized constant Puma::DSL::DefaultRackup (NameError)
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/dsl.rb:131:in `instance_eval'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/dsl.rb:131:in `_load_from'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:235:in `block in load'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:235:in `each'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:235:in `load'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/launcher.rb:54:in `initialize'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/rack/handler/puma.rb:68:in `new'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/rack/handler/puma.rb:68:in `run'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:327:in `start'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:38:in `start'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```
</details>

I think this was the default puma config generated with a Rails 5 app initially (4 years ago). I am not familiar what this setting did before, but after going through the upgrade guide I haven't seen any mention of `rackup`. Worked fine with Puma 5.6.5.

**Puma config:**

```ruby
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3020
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end
```

**To Reproduce**

Make `hello.ru`:

```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

Run it with:

```
bundle exec puma -C <where_your_config_is> hello.ru
```

**Expected behavior**

Upgrade guide instructions should mention this breaking change.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6, M1 Max
 - Puma Version 6

### PR DESCRIPTION
**Pull request by dentarg**
Close #2989

### CODE REVIEW

**Comment by bf4** [comment]
FWIW, I've now added a test that puma boots to our test suite. Sharing for anyone who wants to give it a shot

```ruby
# https://github.com/puma/puma/blob/v6.0.0/test/test_rack_handler.rb
module UniquePort
  def self.call
    TCPServer.open('127.0.0.1', 0) do |server|
      server.connect_address.ip_port
    end
  end
end
RSpec.describe "confirms Puma boots", :slow do
  it "boots puma" do
    require "rack/handler/puma"

    @input = nil
    app = Proc.new {|env| @input = env; [200, {}, ["hello world"]]}
    # conf = Rack::Handler::Puma.config(->{}, @options)
    host = '127.0.0.1'
    port = UniquePort.call
    opts = { Host: host, Port: port }
    in_handler(app, opts) do |launcher|
      hit(["http://#{host}:#{port}/test"])
      expect("/test").to eq( @input["PATH_INFO"])
    end
  end

  def in_handler(app, options = {})
    options[:Port] ||= 0
    options[:Silent] = true

    @launcher = nil
    thread = Thread.new do
      Rack::Handler::Puma.run(app, **options) do |s, p|
        @launcher = s
      end
    end

    # Wait for launcher to boot
    Timeout.timeout(10) do
      sleep 0.5 until @launcher
    end
    sleep 1.5 unless Puma::IS_MRI

    yield @launcher
  ensure
    @launcher&.stop
    thread&.join
  end

  # Either takes a string to do a get request against, or a tuple of [URI, HTTP] where
  # HTTP is some kind of Net::HTTP request object (POST, HEAD, etc.)
  def hit(uris)
    uris.map do |u|
      response =
        without_vcr do
          if u.kind_of? String
            Net::HTTP.get(URI.parse(u))
          else
            url = URI.parse(u[0])
            Net::HTTP.new(url.host, url.port).start {|h| h.request(u[1]) }
          end
        end

      expect(response).to be_present, "Didn't get a response: #{u}"
      response
    end
  end
end
```

**Comment by dentarg** [comment]
@bf4 I have tests like that too, but they're a bit different from yours, I parse the Procfile and start that command, see https://github.com/Starkast/wikimum/blob/95777e39844847afc0cbb68acb3780c07e339d5b/test/integration/app_boot_test.rb

**Comment by bf4** [comment]
yeah, https://github.com/Starkast/wikimum/blob/95777e39844847afc0cbb68acb3780c07e339d5b/test/integration/app_boot_test.rb looks pretty similar in the important bits, though it tests the worker, not web process. I actually think mine (which is extracted from Puma) could probably be simpler, but I threw this spaghetti at the wall and stuck, so I moved on.

Someone else made this shell scripts https://gist.github.com/vojtad/3649aa51c4dd9f9c5ae148e3b3afbbbe

**Comment by bf4** [comment]
Seems my test task above broke in 6.1.0 since https://github.com/puma/puma/pull/3061

```diff
diff --git a/bin/task-puma_boot b/bin/task-puma_boot
index c5a9f8a1c5..86e44b48fc 100755
--- a/bin/task-puma_boot
+++ b/bin/task-puma_boot
@@ -1,6 +1,7 @@
 #!/usr/bin/env ruby
 
 # https://github.com/puma/puma/pull/2990#issuecomment-1279557257
+# https://github.com/puma/puma/pull/3061
 # https://github.com/puma/puma/blob/v6.0.0/test/test_rack_handler.rb
 class TaskPumaBoot
 
@@ -50,6 +51,12 @@ class TaskPumaBoot
     require "pathname"
     require "fileutils"
     FileUtils.mkdir_p(app_root.join("tmp/pids"))
+    require "bundler/setup"
+    # on Rack 3 is
+    # require "rackup"
+    # @rack_handler_mod = ::Rackup::Handler
+    require "rack"
+    @rack_handler_mod = ::Rack::Handler
     require "rack/handler/puma"
   end
 
@@ -60,7 +67,7 @@ class TaskPumaBoot
     instance = self
     instance.launcher = nil
     thread = Thread.new do
-      Rack::Handler::Puma.run(app, **options) do |s, p|
+      @rack_handler_mod::Puma.run(app, **options) do |s, p|
         instance.launcher = s
       end
     end
```

**Comment by MSP-Greg** [comment]
@bf4

I hate it when that happens.  My mistake, I was focused on making sure the `rackup` bin file worked, forgot about starting Puma as you have.  I'll have a PR soon...

**Comment by MSP-Greg** [comment]
@bf4

I believe #3080 fixes the issue, so the patch you listed shouldn't be needed.

If you have time to check it, it would be appreciated.

**Comment by dentarg** [comment]
> yeah, https://github.com/Starkast/wikimum/blob/95777e39844847afc0cbb68acb3780c07e339d5b/test/integration/app_boot_test.rb looks pretty similar in the important bits, though it tests the worker, not web process

Not sure I follow... :) The worker handles web requests? The tests makes web requests

**Comment by bf4** [comment]
@dentarg yeah,  I misread the code first time around.  🙃

**Pull request merged**
