### PR TITLE
replace `while true` with `loop do`

### PR DESCRIPTION
**Pull request by jjb**
Nicer code, and I'm guessing it's a tiny bit more performant

### CODE REVIEW

**Comment by nateberkopec** [comment]
Is there a RuboCop rule we can add for this?

**Comment by nateberkopec** [comment]
benchmarks/wrk/ssl_realistic_response.sh shows no real difference between this and master but I'm OK with changing it anyway as I do like the look of it better + it may matter in the future so I'm ok with merging with a Rubocop rule

**Comment by jjb** [comment]
🚨 loop is actually slower

i thought it might be because maybe loop is implemented in ruby and not C, but [that's not the case](https://github.com/ruby/ruby/blob/master/vm_eval.c#L1328) 🤷 . 

```ruby
require 'benchmark'

TIMES = 100_000_000

def with_while
  i = 0
  while true
    i+=1
    return if i==TIMES
  end
end

def with_while_with_condition
  i = 0
  while 1==1
    i+=1
    return if i==TIMES
  end
end


def with_loop
  i = 0
  loop do
    i+=1
    return if i==TIMES
  end
end

puts "warming up\n"
with_while
with_while_with_condition
with_loop

Benchmark.bm(10) do |x|
  x.report("while") do
    with_while
  end
  x.report("while_with_condition") do
    with_while_with_condition
  end
  x.report("loop") do
    with_loop
  end
end
```

```
                 user     system      total        real
while        1.731089   0.012813   1.743902 (  1.889690)
while_with_condition  2.686485   0.010185   2.696670 (  2.752244)
loop         5.964884   0.045229   6.010113 (  6.293856)
```

**Comment by dentarg** [comment]
Seems like the use of `while true` has been intentional, example: https://github.com/puma/puma/commit/cf44fa7e3267d6b90a6187b1477fcdd3235517d5

**Comment by jjb** [comment]
@dentarg good find! 

spock saying 'fascinating'

**Pull request closed without merging**
