### PR TITLE
[CI] Add workflow to test ragel generation

### LINKED ISSUE #2858: New build step for verifying ragel
Action should:

```
rm ext/puma_http11/http11_parser.c
rm ext/puma_http11/org/jruby/puma/Http11Parser.java

bundle exec rake ragel
```

and then [assert there is no diff against master](https://stackoverflow.com/questions/5139290/how-to-check-if-theres-nothing-to-be-committed-in-the-current-branch)

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

Two files are generated with ragel.  These files may not match the source files.  Add a workflow to test, and save CI generated files if they do not match what is in the repo.

PR opened as a draft with existing workflows disabled, and tests are failing.  See https://github.com/puma/puma/actions/runs/2173139081

Note that all of the puma workflows have 'workflow_dispatch' enabled, so they can be run at anytime on any branch by a member.

Closes #2858

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by dentarg** [comment]
What was https://github.com/puma/puma/commit/a7f48495e8d9ac58d9877aba8a6745c97e5a7abf?

**Comment by MSP-Greg** [comment]
@dentarg

> What was https://github.com/puma/puma/commit/a7f48495e8d9ac58d9877aba8a6745c97e5a7abf?

Not sure.  I suspect @nateberkopec did it locally, not sure why the output he got differs from the output on Actions?

All the Actions OS's are using ragel 6.10.

If you have time, can you check locally and see what your system(s) show?

**Comment by nateberkopec** [comment]
Oh weird. Well I can always revert if something funky is going on locally for me!

**Comment by nateberkopec** [comment]
You're a wizard, @MSP-Greg !

**Comment by MSP-Greg** [comment]
> You're a wizard

We'll just say I'm persistent, know what Actions can do, and know that Powershell is the easiest way to run cross-platform scripts.

Just in case people haven't looked at the Actions pages, if you look at https://github.com/puma/puma/actions/runs/2173139081 in a desktop browser, the bottom of the page is 'Artifacts'.  These are zip files of the ragel generated code, and are only created if the tests fail.  Hence, if things get out of sync, download them, and a PR/commit should fix things.

Lastly, Actions workflows can be setup to only run if certain files change.  I haven't worked with it much, not sure how it works if multiple commits are pushed, etc.  I may experiment with it.

Remember that the ragel workflow (and the others also) can be run manually, one selects which branch to run the workflow on.  
The UX is a bit odd, one has to go to the repo's main Actions page, then select a workflow on the left.  Should see a box with 'This workflow has a workflow_dispatch event trigger.' and a button on the right.  That button runs the workflow...

@nateberkopec

> if something funky is going on locally

What version of ragel generated the files?  I'd really like to see if we can figure why the files don't match.

**Comment by dentarg** [comment]
I'm also using ragel 6.10 (from Homebrew on macOS 12.3.1)

```shell
$ ragel --version
Ragel State Machine Compiler version 6.10 March 2017
Copyright (c) 2001-2009 by Adrian Thurston
```

I can't reproduce https://github.com/puma/puma/commit/a7f48495e8d9ac58d9877aba8a6745c97e5a7abf (not on current master a4b5c2fc nor 1cea90aa (the commit before `regenerate ragel`))


```shell
$ rm ext/puma_http11/http11_parser.c

$ git status --short
 D ext/puma_http11/http11_parser.c

$ bundle exec rake --trace ragel
** Invoke ragel (first_time)
** Invoke ext/puma_http11/http11_parser.c (first_time)
** Invoke ext/puma_http11/http11_parser.rl (first_time, not_needed)
** Execute ext/puma_http11/http11_parser.c
ragel ext/puma_http11/http11_parser.rl -C -G2 -I ext/puma_http11 -o ext/puma_http11/http11_parser.c
** Invoke ext/puma_http11/org/jruby/puma/Http11Parser.java (first_time, not_needed)
** Invoke ext/puma_http11/http11_parser.java.rl (first_time, not_needed)
** Execute ragel

$ git status
On branch master
Your branch is up to date with 'dentarg/master'.

nothing to commit, working tree clean
```

**Comment by MSP-Greg** [comment]
@dentarg Thanks for checking.

**Pull request merged**
