### PR TITLE
fix jruby bug

### PR DESCRIPTION
**Pull request by grosser**
fixes https://github.com/puma/puma/issues/1292

### CODE REVIEW

**Comment by nateberkopec** [comment]
Thanks for fixing this so quickly!

**Comment by grosser** [comment]
maybe wait for travis before merging :D 

```
  2) Failure:
TestIntegration#test_restart_restores_environment [/home/travis/build/puma/puma/test/test_integration.rb:254]:
Expected # encoding: ASCII-8BIT
"Hello RAND 0.8985455927826598" to not be equal to # encoding: ASCII-8BIT
"Hello RAND 0.8985455927826598".
```

**Comment by grosser** [comment]
I'll look into that one next ...

**Comment by nateberkopec** [comment]
I did! that was failing before you, but if you want to fix that too I won't complain :D

**Comment by grosser** [comment]
cannot fail before me since that's a test I added ;)

**Comment by grosser** [comment]
here: https://github.com/puma/puma/pull/1305/files

**Pull request merged**
