### PR TITLE
CI: add Ruby 3.2.0 jobs

### PR DESCRIPTION
**Pull request by dentarg**
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

### CODE REVIEW

**Comment by MSP-Greg** [comment]
When [ruby/setup-ruby/windows-versions.json](https://github.com/ruby/setup-ruby/blob/master/windows-versions.json) includes Ruby 3.2.0, this will pass.

New Windows Ruby versions may take a few days to 'move' thru the system...

**Comment by dentarg** [comment]
Hehe, totally forgot about Windows 🤦‍♂️

I'll rebase once I see that happen

**Comment by MSP-Greg** [comment]
@dentarg

I forgot about one thing.  The current MSYS2 OpenSSL package is 1.1.1.  But, the new Windows Ruby 3.2.0 is built with a custom OpenSSL 3.0.x package.  I haven't hooked that into setup-ruby-pkgs yet.  I might take care of it in setup-ruby.

So, let me get that done also...

**Comment by nateberkopec** [comment]
Woohoo! Merry Christmas, everyone!

**Comment by MSP-Greg** [comment]
> Woohoo! Merry Christmas, everyone!

And to you also.  Sorry, a bit belated...

**Comment by MSP-Greg** [comment]
@dentarg Thanks.  All the Actions updates are finished...

**Pull request merged**
