### PR TITLE
Fix NameError by adding ::operator

### LINKED ISSUE #3117: Failed to initialize Rack::CommonLogger
**Describe the bug**

`Rack::CommonLogger` is failed to initialize because of `NameError` if `Verbose` is set as `true` with:
- `puma` v6.2.1
-  `rack` v3.0.7
- `rackup` v2.1.0

**Puma config:**

Please see the following section.

**To Reproduce**

```ruby
# test.rb

require "rack"
require "rackup"
require "rack/handler/puma"

class App
  def initialize
    @rack_static = Rack::Static.new(
      -> { [404, {}, []] },
      root: File.expand_path("./", __dir__),
      urls: ["/"]
    )
  end

  def call(env)
    @rack_static.call(env)
  end
end

app = Rack::Builder.new do
  run App.new
end.to_app

Rackup::Handler::Puma.run(app, Verbose: true)
```

```bash
$ ruby test.rb
/Users/foo/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.2.1/lib/rack/handler/puma.rb:35:in `block in config': uninitialized constant Puma::Rack::CommonLogger (NameError)

          app = Rack::CommonLogger.new(app, STDOUT)
                    ^^^^^^^^^^^^^^
        from /Users/foo/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.2.1/lib/puma/configuration.rb:195:in `configure'
        from /Users/foo/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.2.1/lib/puma/configuration.rb:188:in `initialize'
        from /Users/foo/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.2.1/lib/rack/handler/puma.rb:32:in `new'
        from /Users/foo/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.2.1/lib/rack/handler/puma.rb:32:in `config'
        from /Users/foo/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.2.1/lib/rack/handler/puma.rb:64:in `run'
        from test.rb:25:in `<main>'
```

**Expected behavior**

`Rack::CommonLogger` is initialized without `NameError`.

**Desktop (please complete the following information):**
 - OS: Mac
 - Puma Version: 6.2.1

### PR DESCRIPTION
**Pull request by ninoseki**
### Description

Closes #3117 by adding `::` operator. 

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Verified #3117 with Ubuntu 22.04 & Ruby master/head.

**Comment by dentarg** [comment]
We must be missing a test case?

**Comment by MSP-Greg** [comment]
@dentarg

Good idea.  See #3119.  Fails if this is reverted.

**Comment by dentarg** [comment]
Excellent, thanks for that @MSP-Greg ❤️

**Pull request merged**
