### PR TITLE
Instrument requests count

### PR DESCRIPTION
**Pull request by ylecuyer**
### Description
For monitoring purpose and in order to create a puma worker killer style plugin (which restart workers after 10k requests) I need to add instrumentation for requests count

I have not yet added test nor the entry in HISTORY.md as I want to be sure this PR wont be rejected before working on this.

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` the pull request title.
- [x] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by nateberkopec** [comment]
LGTM, I think this will work.

**Comment by wjordan** [comment]
This PR seems similar to #2061, in fact the code change is nearly identical. That PR is still in-progress because test coverage was requested (https://github.com/puma/puma/pull/2061#pullrequestreview-310021195).

**Comment by nateberkopec** [comment]
I have no problem merging either, just a matter of who figures out the testing issues first 😆

**Comment by ylecuyer** [comment]
Required tests have been added ;)

**Comment by nateberkopec** [comment]
Wünderbar!

**Pull request merged**
