### PR TITLE
Server#closed_socket? - parameter may be a MiniSSL::Socket

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

Similar code and naming is used `Server#cork_socket` & `Server#uncork_socket`...

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by dentarg** [comment]
Is it correct that without this change, if you use Puma to terminate SSL/TLS, you aren't getting the benefit of https://github.com/puma/puma/pull/1227? 

If that's the case, would be good to change the PR title so that info is reflected in the changelog/history – I didn't understand what this was about until I read [the chat](https://github.com/puma/puma/blob/master/CONTRIBUTING.md) where #1227 was linked :)

**Comment by dentarg** [comment]
> Similar code and **naming** is used `Server#cork_socket` & `Server#uncork_socket`

Yeah I'm not a big fan of "`skt`" 😆 but I will 🙈

**Review by dentarg — COMMENTED** [review]
LGTM

**Review by dentarg — COMMENTED** [review]
Can we test this?

**Comment by dentarg** [comment]
> Can we test this?

I see that https://github.com/puma/puma/pull/1227 didn't add a test, I wonder if tests have been added later on or if this is untested? 🤔

**Comment by MSP-Greg** [comment]
Sorry.  I wasn't clear.  I should have seen it before.

The `MiniSSL::Socket` isn't related to IO or any Socket, it just has a few methods that make it appear `IO` like.  But, it has a `TCPSocket` that it 'connects' with.  So, testing whether `Client#io.is_a? TCPSocket` will never pass, but testing `Client#io.to_io.is_a? TCPSocket` will.  Same thing is done at the start of `cork_socket` and `uncork_socket`.

Or, when passing in a `MiniSSL::Socket` or `OpenSSL::Socket` to methods that also handle `TCPSocket` or `UNIXSocket` , one needs to be careful for what tests/methods are with them...

**Pull request merged**
