### PR TITLE
LibreSSL fix

### PR DESCRIPTION
**Pull request by fmauNeko**
This fixes running an SSL server built against LibreSSL.

Fixes parts of #1181

### CODE REVIEW

**Comment by nateberkopec** [comment]
Hm, do we need a version guard here as well?

**Comment by fmauNeko** [comment]
We don't, the problematic function, `DH_set0_pqg`, was added only to OpenSSL 1.1.0, and not to LibreSSL

**Comment by ernie** [comment]
Popped in here to say this one worked for me today, only to find it just got merged. Thanks!

**Comment by rafmagana** [comment]
This works for me. When is this going to be released?

**Pull request merged**
