### PR TITLE
5.6.5 release note

### PR DESCRIPTION
**Pull request by nateberkopec**

### CODE REVIEW

**Comment by nateberkopec** [comment]
Also thank you for adding all the links 😄

**Comment by MSP-Greg** [comment]
@nateberkopec Ok.  I guess I didn;'t look at the breaking changes' part.  You or I can just delete the features section?

**Comment by nateberkopec** [comment]
Hahah no worries, I'll take it from here. I was mostly just creating the list so I had a list of things to cherry-pick into 5-6-stable.

**Comment by MSP-Greg** [comment]
> I'll take it from here.

Sorry, I removed them with a separate commit.  Some may not involve breaking changes, Not.sure.  Just thinking that if more feature commits are added to 5-6-stable, it will make cherry-picking easier in the future?

**Pull request merged**
