### PR TITLE
Remove Puma::Delegation [changelog skip]

### PR DESCRIPTION
**Pull request by pascalbetz**
Replace with Forwardable.

See #1995

### CODE REVIEW

**Comment by pascalbetz** [comment]
The two failing tests will get fixed with #1987 
Will rebase once fixed.

**Comment by nateberkopec** [comment]
LGTM, let me fix up master and this can get merged.

**Comment by pascalbetz** [comment]
@nateberkopec all green now.

I think it's a great idea to label the easy issues! Will definitely look at other easy ones.

**Comment by nateberkopec** [comment]
Thanks @pascalbetz! And thanks for your contribution.

**Pull request merged**
