### PR TITLE
simplify test shellout and make sure no other version of puma is available so we know our tests work

### PR DESCRIPTION
**Pull request by grosser**
@nateberkopec 
/cc @schneems

### CODE REVIEW

**Comment by grosser** [comment]
updated ... realized I cannot remove bundler since then the gem would not be found (we already run the shellout with bundler since RUBYOPT is set) ... and switching to `bundle exec` does not work without the patch from https://github.com/puma/puma/pull/1309 ... so for now just some cleanup to make the other PRs cleaner

**Comment by nateberkopec** [comment]
@grosser JRuby 9000 should have a green CI, it doesn't: https://travis-ci.org/puma/puma/jobs/238616761

**Comment by grosser** [comment]
error seems to be:
```
  2) Error:
TestIntegration#test_restart_closes_keepalive_sockets:
#<Class:0x3cfe95b1>: execution expired
    org/jruby/RubyIO.java:2233:in `gets'
    /home/travis/build/puma/puma/test/test_integration.rb:93:in `wait_for_server_to_boot'
    /home/travis/build/puma/puma/test/test_integration.rb:82:in `restart_server'
    /home/travis/build/puma/puma/test/test_integration.rb:56:in `restart_server_and_listen'
    /home/travis/build/puma/puma/test/test_integration.rb:208:in `test_restart_closes_keepalive_sockets'
```
already restarted it twice ... reproduced it and turns out the `-Ilib` re-injection did not work on jruby ... so another bug fixed :D

**Comment by grosser** [comment]
added more time to the timeout since it kept failing and on master the test took 59s ... on this branch it took 64 ... so I hope just randomness but now jruby has a bit more time ...

```
time ruby test/test_integration.rb -n 'TestIntegration#test_restart_closes_keepalive_sockets'
```

**Comment by grosser** [comment]
somehow `TestThreadPool#test_trim_is_ignored_if_no_waiting_threads` failed on ruby 2.1 now ... but should be unrealted ...

**Comment by grosser** [comment]
2.1 and jruby are green 🎉

**Pull request merged**
