### PR TITLE
normalize whitespace in worker stats string

### PR DESCRIPTION
**Pull request by jjb**
### Description

i was making another PR to add another type of stat (busy_threads), and noticed this

it's the heroes like me which keep this project afloat.

### Your checklist for this pull request

- [ x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x ] I have updated the documentation accordingly.
- [? ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by jjb** [comment]
https://github.com/puma/puma/pull/2473

**Review by schneems — APPROVED** [review]
Think of all the whitespace bytes we're able to save! 

This is more of a style/refactor which I tend do avoid merging due to conflicts. That being said, normalizing this is nicer and this line doesn't see a lot of churn. Thanks, merging!

**Comment by jjb** [comment]
i have a DRYification coming up so we don't have to repeat the stat array twice, and this helps that a bit

**Pull request merged**
