### PR TITLE
Allow configuring request uri max length & request path max length

### PR DESCRIPTION
**Pull request by LukaszMaslej**
### Description

According to https://github.com/puma/puma/issues/2758 discussion, I add also an optional cflags to configure request uri max length and request path max length when compile puma.

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by dentarg** [comment]
https://github.com/puma/puma/pull/2485 changed more files, is that needed here or not? Thinking of the parser line number changes and possible error messages (I have not checked myself)

**Comment by nateberkopec** [comment]
Welcome to our contributors @LukaszMaslej 😄

**Comment by LukaszMaslej** [comment]
Hi @dentarg 

I did tests if error messages are still fine.

```
#<Puma::HttpParserError: HTTP element QUERY_STRING is longer than the 11111 allowed length (was 11385)>
#<Puma::HttpParserError: HTTP element QUERY_STRING is longer than the 1024*11 allowed length (was 11385)>
#<Puma::HttpParserError: HTTP element REQUEST_PATH is longer than the 9191 allowed length (was 11384)>
#<Puma::HttpParserError: HTTP element REQUEST_URI is longer than the (1024 * 12) allowed length (was 13431)>
#<Puma::HttpParserError: HTTP element REQUEST_URI is longer than the 12000 allowed length (was 13431)>
```
They look to be ok.
Whats about  parser line number changes -  if someone could double check this. Help here will be welcome ;).

**Comment by woutdegeyter** [comment]
@nateberkopec @dentarg Thank you for the quick reactions.
Is there any chance that this could get merged into master soon (and even better, a tag could get created)?

We have a client that is blocked by this.
If this couldn't get merged into master soon, we would create a fork based on Lukasz' branch. But that is obviously less ideal :). 

Thanks already.

**Comment by dentarg** [comment]
@woutdegeyter Yeah, no that not how open source works, we are not merging anything sooner than later just because _your_ client needs it, maybe help out instead? Why was the parser changes done #2485?

**Comment by LukaszMaslej** [comment]
@dentarg I checked if error messages are formatted as they should be. It was discussed ([comment]( https://github.com/puma/puma/pull/2485#issuecomment-726878369)) for https://github.com/puma/puma/pull/2485 PR.  I wanted to be sure it is still fine when use my new flags.

I tested different ways how the flag could be set (that's why there are two samples), like for example `bundle config build.puma "--with-cflags='-D PUMA_REQUEST_PATH_MAX_LENGTH=9191'"` or `bundle config build.puma "--with-cflags='-D PUMA_QUERY_STRING_MAX_LENGTH=1024*11'"`.

I made only these basic changes, but worth to check by some one more advanced in C to check parser files.

**Comment by MSP-Greg** [comment]
> Why were the parser changes done https://github.com/puma/puma/pull/2485?

Referring to the changes in [`ext/puma_http11/http11_parser.c`](https://github.com/puma/puma/pull/2485/files#diff-3e935c662ed5a835cca189ac2364ecf504fe38db517f3d287299be552d842e9a)?

I don't think this changes that file (delete it, and run `rake ragel`).  But, not sure about changes for JRuby?

**Comment by LukaszMaslej** [comment]
@MSP-Greg Thanks, I removed  `ext/puma_http11/http11_parser.c` and run `rake ragel`. Files are identical.

@dentarg  To question about parser changes, `ext/puma_http11/http11_parser.c` does not need changes this time.

**Comment by LukaszMaslej** [comment]
Hi @dentarg 
> https://github.com/puma/puma/pull/2485 changed more files, is that needed here or not? Thinking of the parser line number changes and possible error messages (I have not checked myself)

Replying here -  I believe both points are satisfied. The parser lines don't need update now [comment](https://github.com/puma/puma/pull/2840#issuecomment-1068137226), the error messages are returned as expected (see my [comment](https://github.com/puma/puma/pull/2840#issuecomment-1066669875)). Or there is something more I should check here?

**Comment by LukaszMaslej** [comment]
@dentarg Thank you for merge to master. Kind question, do you plan new version release in some near future?

**Comment by dentarg** [comment]
I don't do the releases! Sorry

**Comment by LukaszMaslej** [comment]
Yes, my bad, sorry. 
@nateberkopec just repeat my kind question for next release ;).
Do you plan it somehow in near future?

**Pull request merged**
