### PR TITLE
WIP CLI: Args over config

### PR DESCRIPTION
**Pull request by chulkilee**
**WIP - feedback is welcome**

- [x] add option to use args over config to keep the existing behavior.
- [ ] keep the existing behavior for `binds` option

See also #460

### CODE REVIEW

**Comment by evanphx** [comment]
This looks totally fine, both is idea and execution. Was there more you wanted to put into it?

**Comment by chulkilee** [comment]
Apparently there is a bug in this PR so the test app server fails to start (and CI gets timeout error). I'm going to rebase it after #672 is merged to master to minimize the code change of this PR.

**Comment by evanphx** [comment]
The timeout is probably not because of your code. Looks like things aren't behaving properly on 2.2.

**Comment by frodsan** [comment]
@evanphx Hi, I upgrade puma to 2.13.0 and I'm having some problems in Heroku.

In version 2.12.3, the port is correctly binded.

```
$ PORT=123132 bundle exec puma -C config/puma.rb
[904] Puma starting in cluster mode...
[904] * Version 2.12.3 (ruby 2.2.2-p95), codename: Plutonian Photo Shoot
[904] * Min threads: 5, max threads: 5
[904] * Environment: development
[904] * Process workers: 2
[904] * Preloading application
[904] * Listening on tcp://0.0.0.0:123132
```

In version 2.13.0, it takes the default port even when I assign a different one.

```
$ PORT=123132 bundle exec puma -C config/puma.rb
[909] Puma starting in cluster mode...
[909] * Version 2.13.0 (ruby 2.2.2-p95), codename: A Midsummer Code's Dream
[909] * Min threads: 5, max threads: 5
[909] * Environment: development
[909] * Process workers: 2
[909] * Preloading application
[909] * Listening on tcp://0.0.0.0:9292
```

This is my config file:

```ruby
workers_count = Integer(ENV["PUMA_WORKERS"] || 2)
threads_count = Integer(ENV["PUMA_MAX_THREADS"] || 5)

workers workers_count
threads threads_count, threads_count

rackup      DefaultRackup
port        ENV["PORT"]
environment ENV["RACK_ENV"]

preload_app!
```

Thanks in advance!

**Comment by dwilkie** [comment]
+1

This is causing elastic beanstalk to break as well. `bind` is ignored in the configuration file

**Pull request closed without merging**
