### PR TITLE
Try Github Actions

### PR DESCRIPTION
**Pull request by nateberkopec**
* [ ] Ruby 2.2
* [x] Windows 
* [x] Mac
* [ ] OpenSSL 1.0.1 & 1.0.2
* [ ] JRuby latest
* [ ] JRuby and Ruby head

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Re Windows & GitHub Actions, it's not quite ready for Ruby use, mostly due to issues with the build tools (MSYS2).

When that's clear what direction it's going, that will be the time to convert Windows CI, and add bundler...

**Comment by nateberkopec** [comment]
> GA is fast. Will be interesting to see how many test files can run parallel...

Yeah, this is probably the most interesting part. I hope they can keep the speed as they scale up.

**Comment by MSP-Greg** [comment]
Windows with bundler, running everything that Actions currently has:

https://github.com/MSP-Greg/puma/runs/208343467

1. Windows jobs use some code of mine (custom GitHub Actions) to connect with the MSYS2 system.

2. `ENV['CI']` isn't set on Actions

3. Actions Windows Ruby currently has three MSYS2 installs, each embedded in the Ruby install.  Windows Ruby 2.4.x is building with OpenSSL 1.1.1., and it should be building with 1.0.2.  But, it seems that the 2.5.x and 2.6.x MSYS2 installs have OpenSSL 1.0.2 installed, which the 'actions' updates.  Confused.

4. Still seeing intermittent failures/errors, mostly on macOS with my favorite test.

5. The Actions people seem receptive to getting this working...

Regardless, have a good weekend...

**Comment by MSP-Greg** [comment]
In the file you just pushed:
```
    - name: RubyGems, Bundler Update
      run:  gem update --system --no-document --conservative
    - name: bundle install
      run: |
        gem update --system --no-document --conservative
        bundle install --jobs 4 --retry 3
```

The same steps in my fork:
```
    - name: RubyGems, Bundler Update
      run:  gem update --system --no-document --conservative
    - name: bundle install
      run:  bundle install --jobs 4 --retry 3
```

It would appear that the two line 'bundle install' `run:` isn't running the second line, which leaves the 'compile' step without `rake-compile`.  Obviously, a bug on Actions.  I checked, and none of my testing used mutli-line `run:` strings.  I know some of the shell stuff is not working as expected.

If you have a minute, try changing it and see if windows compiles...

I hate new CI.  Spent enough time on Azure Pipelines to only have it superseded by GitHub Actions.  I hope to get a Ruby Windows trunk build as a GitHub release as soon as they get Actions a little further along.

**Comment by nateberkopec** [comment]
Something weird is going on with Mac and `test_term_closes_listeners`.

**Comment by MSP-Greg** [comment]
> Something weird is going on with Mac and test_term_closes_listeners.

Yes.  Intermittent, more common in Actions, but occurs in Travis also.  I gave up, I added the following in PR #1956

https://github.com/MSP-Greg/puma/blob/ea2c264f2dbf002dcc7ef6b76c20e19a7b05b093/test/test_integration.rb#L533-L541

```ruby
# used with thread_run to define correct 'refused' errors
def thread_run_refused(unix: false)
  if unix
    DARWIN ? [Errno::ENOENT, IOError] : [Errno::ENOENT]
  else
    DARWIN ? [Errno::ECONNREFUSED, Errno::EPIPE, EOFError] :
      [Errno::ECONNREFUSED]
  end
end
```

**Comment by nateberkopec** [comment]
The [broken pipe](https://github.com/puma/puma/pull/1918/checks?check_run_id=218917461#step:9:204) is weird.

**Comment by MSP-Greg** [comment]
> The broken pipe is weird.

As I recall, I have never seen the failure on (a lot of) Ubuntu jobs.

It does fail more consistently on Actions.  See Issue #1930, which was before Actions was even being used.

It's something I was too worn out to test more, I hope to debug more later...

**Comment by MSP-Greg** [comment]
No JRuby yet on Actions.  Can be done with RVM.  See:

https://github.com/rubygems/rubygems/blob/master/.github/workflows/ubuntu-rvm.yml

**Comment by nateberkopec** [comment]
https://github.com/actions/setup-ruby/issues/20

**Comment by nateberkopec** [comment]
gonna smash that merge button and just open an issue for remaining things.

**Pull request merged**
