### PR TITLE
fix #1775

### LINKED ISSUE #1775: Socket removed after reload
### Steps to reproduce

I followed instruction on the wiki to setup puma with systemd on Ubuntu 18.04 (https://github.com/puma/puma/blob/master/docs/systemd.md#socket-activation) but puma reload is not working as expected with the latest version of puma.

During a reload, I see these logs which highlight the problem (with `PUMA_DEBUG=1`):

> Apr 16 03:38:22 fizz bundle[1184]: % Registered unix:/home/app/web/shared/tmp/sockets/puma.sock for activation from LISTEN_FDS
> Apr 16 03:38:22 fizz bundle[1184]: [1184] Puma starting in cluster mode...
> Apr 16 03:38:22 fizz bundle[1184]: [1184] * Version 3.12.1 (ruby 2.5.5-p157), codename: Llamas in Pajamas
> Apr 16 03:38:22 fizz bundle[1184]: [1184] * Min threads: 8, max threads: 16
> Apr 16 03:38:22 fizz bundle[1184]: [1184] * Environment: production
> Apr 16 03:38:22 fizz bundle[1184]: [1184] * Process workers: 2
> Apr 16 03:38:22 fizz bundle[1184]: [1184] * Phased restart available
> Apr 16 03:38:22 fizz bundle[1184]: [1184] * Activated unix:///home/app/web/shared/tmp/sockets/puma.sock
> Apr 16 03:38:22 fizz bundle[1184]: [1184] Use Ctrl-C to stop
> Apr 16 03:38:25 fizz bundle[1184]: [1184] - Worker 1 (pid: 1225) booted, phase: 0
> Apr 16 03:38:25 fizz bundle[1184]: [1184] - Worker 0 (pid: 1221) booted, phase: 0
> Apr 16 03:38:43 fizz systemd[1]: Reloading Puma HTTP Server.
> Apr 16 03:38:43 fizz bundle[1184]: [1184] - Starting phased worker restart, phase: 1
> Apr 16 03:38:43 fizz bundle[1184]: [1184] + Changing to /home/app/web/current
> Apr 16 03:38:43 fizz systemd[1]: Reloaded Puma HTTP Server.
> Apr 16 03:38:45 fizz bundle[1184]: [1184] - Stopping 1221 for phased upgrade...
> Apr 16 03:38:45 fizz bundle[1184]: [1184] - TERM sent to 1221...
> Apr 16 03:38:49 fizz bundle[1184]: [1184] - Worker 0 (pid: 1302) booted, phase: 1
> Apr 16 03:38:49 fizz bundle[1184]: [1184] - Stopping 1225 for phased upgrade...
> Apr 16 03:38:49 fizz bundle[1184]: [1184] - TERM sent to 1225...
> Apr 16 03:38:49 fizz bundle[1184]: Exception handling servers: No such file or directory @ apply2files - /home/app/web/shared/tmp/sockets/puma.sock (Errno::ENOENT)
> Apr 16 03:38:49 fizz bundle[1184]: /home/app/web/shared/bundle/ruby/2.5.0/bundler/gems/puma-200c95d30c37/lib/puma/binder.rb:53:in `unlink'
> Apr 16 03:38:49 fizz bundle[1184]: /home/app/web/shared/bundle/ruby/2.5.0/bundler/gems/puma-200c95d30c37/lib/puma/binder.rb:53:in `block in close'
> Apr 16 03:38:49 fizz bundle[1184]: /home/app/web/shared/bundle/ruby/2.5.0/bundler/gems/puma-200c95d30c37/lib/puma/binder.rb:53:in `each'
> Apr 16 03:38:49 fizz bundle[1184]: /home/app/web/shared/bundle/ruby/2.5.0/bundler/gems/puma-200c95d30c37/lib/puma/binder.rb:53:in `close'
> Apr 16 03:38:49 fizz bundle[1184]: /home/app/web/shared/bundle/ruby/2.5.0/bundler/gems/puma-200c95d30c37/lib/puma/server.rb:939:in `graceful_shutdown'
> Apr 16 03:38:49 fizz bundle[1184]: /home/app/web/shared/bundle/ruby/2.5.0/bundler/gems/puma-200c95d30c37/lib/puma/server.rb:419:in `handle_servers'
> Apr 16 03:38:49 fizz bundle[1184]: /home/app/web/shared/bundle/ruby/2.5.0/bundler/gems/puma-200c95d30c37/lib/puma/server.rb:354:in `block in run'
> Apr 16 03:38:52 fizz bundle[1184]: [1184] - Worker 1 (pid: 1327) booted, phase: 1

After the reload, the workers process are reloaded & running, but nginx isn't serving anything after that point since the `puma.sock` socket is removed (not only closed, but the file itself is not there anymore). 

I think that removing the `@own_binder` logic in #1685 may now cause puma to incorrectly unlink socket as `Puma::Binder#close` does unlink unix socket files and is not doing so in the correct order during a phased restart (unlink occurs after the new workers are spawned, when old workers are stopped) : 

https://github.com/puma/puma/blob/200c95d30c37286c57ed2fc9f87c76365d5f582e/lib/puma/binder.rb#L51-L54

### Expected behavior

Should keep working via unix socket after reload.

### Actual behavior

Unix socket is removed after being activated by new restarted worker.

### System configuration

**Ruby version**: 2.5.5
**Rails version**: 5.1.6.2
**Puma version**: master

---

**Edit:** Just for your information, sadly I am now using port binding with my systemd setup (without any issue). Thanks to everyone investigating & trying to fix those socket issues.

### PR DESCRIPTION
**Pull request by Fudoshiki**
#1775

### CODE REVIEW

**Comment by nammosov** [comment]
works for me, will wait for a release with this fix

**Comment by nateberkopec** [comment]
Will investigate, but needs a test.

**Comment by Fudoshiki** [comment]
I don't know what should test in this case

Would be perfect
1. Start puma server via unix socket with some workers
2. Run smart restart via **pumactl**
3. Check what old workers doesn't get new requests
4. Check what **puma.sock** exists
5. Check what puma server can receive new incoming requests

**Comment by schneems** [comment]
Here's an example of a pretty involved integration test, this file would the be the best place to start https://github.com/puma/puma/pull/1808/commits/184e1510a97c236c6b7ab345e6508559f757045a

**Comment by Fudoshiki** [comment]
I checked 

- pumact stop
- pumactl restart

When server is stoped, puma.sock doesn't exist
WHen restat, file is exist

Assertion fails with `File.unlink i`

**Comment by Fudoshiki** [comment]
@nateberkopec @schneems  Please review this

**Comment by phoet** [comment]
❤️  would be great to see a fixed version for this today, otherwise we would have to rollback in order to have a deployable application...

**Comment by nateberkopec** [comment]
It's a holiday weekend in the USA (where all the maintainers live), please don't set a timeline on our releases.

The code is out there, it's trivial to apply that patch to your own Puma dependency and deploy it if you think it's ready to go.

**Comment by phoet** [comment]
i'm going to interpret this as "dude, so bad that you had a downtime because of this regression, but we are currently enjoying one of the few holidays that we have in turbocapitalisitic turmpstanian. because of that there will probably not be a new version until next week. as you can see, we have not finished to review this change and the safest option for you would be to roll back to 3.X"

**Comment by daveallie** [comment]
@phoet while it obviously isn't an ideal situation to have the latest release not function for specific setups (mine included), Nate and Richard are working for free between day jobs, so cut them some slack.

We also suffered some downtime, but such is the life of early adopters of major version bumps. If you're freezing deploys to prevent 4.x reaching your stack again, then that's an issue with your infrastructure situation, not the speed of releases of Puma. Changing back to 3.x and rolling forward should be as easy as the original update.

There's no need to drop snide comments.

**Comment by phoet** [comment]
i would have appreciated clear insturctions or an expectation of when this going to be released in order to take precautions.

i percived the comment of @nateberkopec as aggressive, the very least it was not helpful in my situation. i'm not a native speaker, so there might be a misunderstanding here.

**Comment by daveallie** [comment]
I don't imagine that was Nate's intent, but even it was, escalating the situation doesn't help anyone. This is all off-topic, let's just stick to updates surrounding this PR from here on out.

**Comment by nateberkopec** [comment]
I would like to release a 4.0.1 by the end of the week. I realize GitHub doesn't make milestones obvious, but that work is [here](https://github.com/puma/puma/milestone/4).

**Comment by schneems** [comment]
One last thing, can you add an entry to HISTORY.md under bugfixes ?

**Comment by schneems** [comment]
Confirmed the test fails on master and passes on this commit.

**Comment by nateberkopec** [comment]
Thanks for the patch @Fudoshiki!

**Comment by nateberkopec** [comment]
This is creating problems in the tests because now created unix listeners are never destroyed.

**Pull request merged**
