### PR TITLE
Exclude status from control-token check (#2081)

### PR DESCRIPTION
**Pull request by tkishel**
Prior to this commit ...

Puma allows access to all (control and status) actions via the same token.

With this commit ...

Puma does not require a token to access status actions.

### Description
Please describe your pull request. Thank you for contributing! You're the best.

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` the pull request title.
- [x] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by tkishel** [comment]
As per this comment in the Issue:

> No, it just means we're over-securing status.

**Comment by nateberkopec** [comment]
Sorry, I should have been more clear. Over-securing status != status should be open to the world. I was more trying to agree with your assertion that there are two separate authorization levels here that we need to distinguish.

I am still in favor of my original proposal of keeping the original behavior and then allowing a configurable proc/lambda. That lets people implement whatever scheme they want.

TBH when it comes to security behavior, everyone has weird opinions and you have to let people do what they want. One-size-fits-all authorization schemes are guaranteed to piss someone off.

**Comment by tkishel** [comment]
I'm happy to contribute towards this, but reluctant to second-guess an implementation.

Could you provide some psuedo-code, or more specifics?

**Comment by nateberkopec** [comment]
In your config, you should be able to provide a lambda. The lambda receives some arguments (I guess: the action name, the provided token, the configured 'correct' token. Maybe we can provide more too?). Returning false means that you are not authorized, and we return a 403. Returning true means you are authorized and we continue.

**Comment by nateberkopec** [comment]
BTW thanks for all of your contributions on this. You've done a lot of work here!

**Comment by tkishel** [comment]
I appreciate you saying that. I'll see what I can do ...

**Pull request closed without merging**
