### PR TITLE
More elaborate exception handling.

### LINKED ISSUE #2699: Puma listen thread can fail with infinite loop.
The following middleware can cause Puma to enter an infinite loop:

``` ruby
require 'objspace'

run lambda{|env|
	ios = ObjectSpace.each_object(IO).to_a.select{|io| io.is_a?(TCPServer)}
	
	ios.each(&:close)
	
	[200, [], [ios.inspect]]
}
```

This probably seems odd, but we are actually seeing some variant of this in a production system. We don't know who is calling close (suspect threading bug) but it causes an EBADF error in the list loop, followed by infinite `IOError`s:

```
> puma -w4 -t4
[95960] Puma starting in cluster mode...
[95960] * Puma version: 5.4.0 (ruby 3.0.2-p107) ("Super Flight")
[95960] *  Min threads: 4
[95960] *  Max threads: 4
[95960] *  Environment: development
[95960] *   Master PID: 95960
[95960] *      Workers: 4
[95960] *     Restarts: (✔) hot (✔) phased
[95960] * Listening on http://0.0.0.0:9292
[95960] Use Ctrl-C to stop
[95960] - Worker 1 (PID: 95962) booted in 0.02s, phase: 0
[95960] - Worker 0 (PID: 95961) booted in 0.02s, phase: 0
[95960] - Worker 2 (PID: 95963) booted in 0.02s, phase: 0
[95960] - Worker 3 (PID: 95964) booted in 0.02s, phase: 0
2021-09-15 20:56:09 +1200 Listen loop: #<Errno::EBADF: Bad file descriptor>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
2021-09-15 20:56:09 +1200 Listen loop: #<IOError: closed stream>
```

At the very least, we should probably handle this more gracefully (i.e. exit the loop as soon as the listening socket becomes invalid for any reason, rather than trying to select/accept again).

### PR DESCRIPTION
**Pull request by ioquatix**
Fixes #2699.

### CODE REVIEW

**Comment by nateberkopec** [comment]
Can you adapt the code you put in your issue report into a test? Otherwise LGTM

**Comment by ioquatix** [comment]
@nateberkopec please tell me any nits or other issues with this PR. I am not fully across the Puma test suite so I just cobbled something together from some of the other integration tests.

**Comment by MSP-Greg** [comment]
@ioquatix

I was waiting for CI.  For a test, see:

https://github.com/MSP-Greg/puma/commit/c358b3b14d939ba04e800662b237d79fbeb9a24e.patch

Test & Master https://github.com/MSP-Greg/puma/actions/runs/1239898360
All appropriate runs failed 'TestIntegrationSingle#test_closed_listener'

Test & PR2700 https://github.com/MSP-Greg/puma/actions/runs/1239909432
All appropriate runs passed 'TestIntegrationSingle#test_closed_listener'

Windows is skipped due to the test using SIGTERM.  As mentioned, I tested closing the server, which is where the infinite loop happened.  I needed to add a timeout so the infinite loop was caught if it happened, like with master...

**Comment by ioquatix** [comment]
@MSP-Greg do you want to just add your commit to my commit? I am happy for you to delete my test changes.

**Comment by MSP-Greg** [comment]
@ioquatix

Thanks.  Sorry for the delay.  I squashed to remove your test, I saved the code in a patch file if...

**Review by MSP-Greg — APPROVED** [review]

**Comment by ioquatix** [comment]
My test was a total hack. I am happy you did something better :) Thanks for your commitment to Puma.

**Comment by ioquatix** [comment]
Also it should be said, that there is a material change to the listen loop - `rescue Object` changed to `rescue StandardError`. This means non-`StandardError` exceptions will propagate out and I think that's desirable since these often represent critical failures like memory allocation errors, etc. Basically, at this point, we should let the instance fail. In our production bug... the load balancer continues to try and send traffic for a short while and we end up with a whole batch of failed requests. I'd rather have it fail fast.

**Comment by nateberkopec** [comment]
> Also it should be said, that there is a material change to the listen loop

Yeah, I think I'm willing to call this a bugfix rather than an API change.

**Comment by dentarg** [comment]
> Maybe I'm misunderstanding what's going on, but we are now re-raising the exception on `EBADF`.
> 
> I would expect this to log from this line: https://github.com/puma/puma/blame/master/lib/puma/server.rb#L376 ([permalink](https://github.com/puma/puma/blame/d048ea0308de196972e38e18a0fab0c70ec848fe/lib/puma/server.rb#L376))

@ioquatix That showed up in CI, see https://github.com/puma/puma/pull/2748

**Pull request merged**
