### PR TITLE
6.5.0 [ci skip]

### LINKED ISSUE #3395: Produce new release
**Is your feature request related to a problem? Please describe.**
There hasn't been a release since 8 Jan. There's been a lot of fixes and enhancements since then. 

**Describe the solution you'd like**
It would be helpful to get a new release produced so users can take the latest changes.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by willayton**
### Description
Bump the version for a new tag to be cut. Update history file.

Closes #3395

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [n/a] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by willayton** [comment]
> Question for maintainer - looking at Release.md, I think I'm meant to update the codename in const.rb. What should it be updated to? I'm not seeing the pattern in previous codenames!

Hey @dentarg - any feedback on this question?

**Comment by dentarg** [comment]
@willayton Yeah there is no pattern, sometimes @nateberkopec lets a contributor pick the title and sometimes he just picks one himself

**Comment by dentarg** [comment]
> sometimes @nateberkopec lets a contributor pick the title

Most often the one with most contributions

**Comment by stanhu** [comment]
@nateberkopec Is there anything else we can help with to get this release cut?

**Comment by willayton** [comment]
@dentarg is there any way we can get this release out without @nateberkopec?

**Comment by dentarg** [comment]
Not to my knowledge

**Comment by sams-stripe** [comment]
Thanks for putting this PR together @willayton.  Would also love to see this release get cut!

**Pull request closed without merging**
