### PR TITLE
Revert "Always send lowlevel_error response to client (#2731)"

### PR DESCRIPTION
**Pull request by dentarg**
This reverts commit f8acac1f0702fea1a4f88d68a40bb2f53650b14c.

In response to https://github.com/puma/puma/issues/2808

### CODE REVIEW

**Comment by olleolleolle** [comment]
@dentarg The issue with truffleruby there, could that be sidestepped by a `gem install bundler` _just_ for that Ruby, in that job?

**Comment by dentarg** [comment]
@olleolleolle Maybe, but I don't think we should need to do that? On the other hand, all MRI jobs have this the argument `setup-ruby-ref: MSP-Greg/ruby-setup-ruby/gem-update` to `MSP-Greg/setup-ruby-pkgs@v1` whereas non-MRI jobs don't have that

 Ping @MSP-Greg

**Comment by dentarg** [comment]
Hmm, it failed with plain ruby/setup-ruby too: https://github.com/dentarg/puma/runs/4971018457?check_suite_focus=true

@eregon Is this an issue in ruby/setup-ruby or with TruffleRuby?

**Comment by eregon** [comment]
Already reported as https://github.com/oracle/truffleruby/issues/2586.
Seems the combination of latest bundler + truffleruby 22.0 is problematic (truffleruby-head + bundler shipped with truffleruby works, 21.3 + latest bundler works too).

**Pull request merged**
