### PR TITLE
CI: Use `Tempfile.create` in `TestIntegration`

### PR DESCRIPTION
**Pull request by dentarg**
Hopefully more stable:
- https://github.com/puma/puma/pull/3408#issuecomment-2153329320

Similar change as https://github.com/puma/puma/pull/3296

### CODE REVIEW

**Comment by ioquatix** [comment]
The reason why I assigned it to an instance variable was to prevent GC. So I'm not sure why this change is required, however, I'm also not sure my change fixed the issue, since we saw some other IO related issue... I need to spend more time investigating this too.

**Review by MSP-Greg — COMMENTED** [review]
Maybe:
```ruby
if @config_file&.exist?
  @config_file.unlink
  @config_file = nil
end
```

**Comment by MSP-Greg** [comment]
> The reason why I assigned it to an instance variable was to prevent GC.

Agree, that is an issue. A lot of these issues may be related to running test parallel, along with 'resource starved' CI runners.  In the test update (which I haven't looked at for a while), I think I removed all the `Tempfile.new` use, along with a lot of fixes for blocking IO, etc,  It was a lot more stable.  There were a few lib file changes, so I started on extracing them, but haven't finished...

Re `Tempfile.create`, since we know that `unlink` will always run, why create finalizers?

**Comment by dentarg** [comment]
All tests here are green so let's merge this and see how it plays out going forward?

**Review by MSP-Greg — APPROVED** [review]

**Comment by MSP-Greg** [comment]
@ioquatix I suspect if something stopped `teardown`, it's pretty severe, like a SEGV...

**Pull request merged**
