### PR TITLE
update travis rubies - 2.3.8, 2.4.5, 2.5.3

### PR DESCRIPTION
**Pull request by MSP-Greg**

### CODE REVIEW

**Comment by olleolleolle** [comment]
@MSP-Greg Oh, great, and now could we also add 2.6.0 in the CI matrix - in this PR?

**Comment by MSP-Greg** [comment]
@olleolleolle

Being rather *nix/MacOS challenged, might you have time to look at why trunk was failing when it was 2.6.0?

IOW, I can add it, but I think it will fail.  I believe the failing tests all involve `fork`, so I can't test on Windows...

**Comment by olleolleolle** [comment]
**Update**: My findings were: there's a `[45198] - Gracefully shutting down workers...` where I stalled.

**Comment by MSP-Greg** [comment]
@olleolleolle

Thanks.  I didn't state it above, but the 2nd commit in this PR fixes the [2.2.10 Travis failure](https://travis-ci.org/puma/puma/builds/473081246), as shown in your PR #1695...

**Comment by schneems** [comment]
Thanks a ton!

**Pull request merged**
