### PR TITLE
Let's use Rubocop!

### LINKED ISSUE #1149: Rubocop w/limited ruleset
Taking a look at how [Rails does it](https://github.com/rails/rails/blob/master/.rubocop.yml), we could probably benefit from Rubocop with a limited set of cops (all-off-by-default).

### PR DESCRIPTION
**Pull request by palkan**
Closes #1149.

I've added very basic, all-off-by-default, Rubocop config, which passes. It contains mostly Performance and Layout cops.

Also, I've added a TODO config which contains cops producing a small number of offenses – so, we can easily fix them and make the code style more consistent.

There is the output of the `rubocop -f o -c .rubocop_todo.yml` command:

```
29   Layout/SpaceAroundOperators
21   Layout/SpaceInsideBlockBraces
18   Metrics/LineLength
16   Layout/SpaceAroundEqualsInParameterDefault
15   Layout/SpaceBeforeBlockBraces
15   Layout/SpaceInsideHashLiteralBraces
8    Layout/EmptyLines
6    Layout/EmptyLinesAroundMethodBody
     Layout/EmptyLinesAroundModuleBody
5    Layout/IndentationWidth
4    Layout/EmptyLinesAroundClassBody
3    Layout/AccessModifierIndentation
2    Style/WhileUntilModifier
1    Metrics/ParameterLists
1    Performance/RedundantBlockCall
1    Performance/RedundantMatch
1    Performance/StringReplacement
1    Style/TernaryParentheses
--
152  Total
```

### CODE REVIEW

**Comment by nateberkopec** [comment]
Wonderful!

1. Let's add this to the default rake task. ```task :default => [:rubocop, :test]```
2. Let's add this to CI. ```script: "TESTOPTS=-v bundle exec rake"``` rather than rake test.

**Comment by nateberkopec** [comment]
Rubocop needs to be added to the 2.1 gemfile as well

**Comment by palkan** [comment]
Oh, sorry, didn't noticed that one(

**Comment by nateberkopec** [comment]
It looks like Rubocop is running against vendored stuff. I think you need to add them to the excludes in both rubocop.yml and the Rakefile.

**Comment by palkan** [comment]
Done!

**Comment by nateberkopec** [comment]
Thanks!

**Pull request merged**
