### PR TITLE
NullIO#closed? should return false

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

Currently returns `true`.

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@eregon Sorry for the ping.  The test mentioned above fails frequently on truffleruby.  Every time I've seen the error, I check truffleruby-head, and it passes there.  The test is [here](https://github.com/puma/puma/blob/3d24dc5936d0e570376fa843a682cf2c5481041e/test/test_puma_server.rb#L887-L925).  If you have any ideas...

JFYI, Puma is testing on Windows mswin...

**Comment by eregon** [comment]
I have no specific idea, I think adding the skip is fine here if needed, although a check against `RUBY_ENGINE_VERSION` would be better since it seems already fixed on truffleruby-head (and so should be for the next release as well).

The `sleep 0.1` in that test are probably very timing-sensitive though (and make the test slow), that should probably be avoided if possible.

**Comment by MSP-Greg** [comment]
> a check against RUBY_ENGINE_VERSION

I'm a bit TruffleRuby challenged.  Would `RUBY_ENGINE_VERSION < '22.2'` be okay?  Or, something a bit more complicated?

> The sleep 0.1 in that test are probably very timing-sensitive though (and make the test slow

Given how long a few other tests take, not concerned about time.  Also, some of the timing is related to Actions (one VM on a four VM system).  Or, many of the test delays aren't needed when I run locally...

**Comment by eregon** [comment]
`omit unless Gem::Version.new(RUBY_ENGINE_VERSION) > Gem::Version.new('22.1')` seems more robust and is true for both `22.2.0-dev-8839057f` and upcoming 22.2.

**Comment by MSP-Greg** [comment]
@eregon - Thanks, updated.

**Pull request merged**
