### PR TITLE
Update config.rb

### PR DESCRIPTION
**Pull request by schneems**

### CODE REVIEW

**Comment by nateberkopec** [comment]
Total garbage, who would ever merge this?

**Comment by nateberkopec** [comment]
LOLJK

**Comment by schneems** [comment]
😂🎉

**Comment by thefonso** [comment]
I'm sorry, I lost. what is the purpose of this file? Where does it go? I followed the conversation located here...https://github.com/puma/puma/issues/1211

And I do not understand how this file fits into that previous conversation?

**Comment by nateberkopec** [comment]
This file is literally just an example puma config file. It doesn't actually get used anywhere. AFAICT is was linked from #1211 because the `directory` setting is useful.

**Pull request merged**
