### PR TITLE
CI: update client certs example files

### PR DESCRIPTION
**Pull request by tannakartikey**
### Description
I see that tests are failing on recent PRs due to SSL. With the reference of #2333, I regenerated the certs with  the following command:

```shell
ruby examples/puma/client-certs/generate_client_test.rb
```

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by dentarg** [comment]
I don't think all certs needs to be updated. I updated some in https://github.com/puma/puma/pull/3426 recently. I can update them later.

**Comment by MSP-Greg** [comment]
@dentarg

I haven't looked at the generation code yet, but having all certs expire on the same date would minimize commits needed to keep them current?

Also, I think #3441 fixes the other (non-intermittent) problems currently in CI.  Hence, combining cert updates (this PR?) and #3441 should get CI back to running as before...

**Comment by tannakartikey** [comment]
I think it'd be awesome if we can automate cert generation. I haven't
looked into the code though. I'll create a discussion once I've had a
chance.

Thanks for looking at the PR guys.

**Comment by dentarg** [comment]
Sorry, I was too quick, this PR only updates certs (and keys) in `examples/puma/client-certs` and https://github.com/puma/puma/pull/3426 updated files in `examples/puma/chain_cert`

Yeah I makes sense to update all at the same time :) And automate it if we can. It doesn't need to happen here, let's merge this.

Before this PR

```shell
~/src/puma master
$ find examples/puma/client-certs -name '*.crt' -print -exec sh -c 'openssl x509 -in {} -noout -text | grep -A2 Validity' \;
examples/puma/client-certs/client.crt
        Validity
            Not Before: Aug  1 00:00:00 2020 GMT
            Not After : Aug  1 00:00:00 2024 GMT
examples/puma/client-certs/ca.crt
        Validity
            Not Before: Aug  1 00:00:00 2020 GMT
            Not After : Aug  1 00:00:00 2024 GMT
examples/puma/client-certs/client_unknown.crt
        Validity
            Not Before: Aug  1 00:00:00 2020 GMT
            Not After : Aug  1 00:00:00 2024 GMT
examples/puma/client-certs/server.crt
        Validity
            Not Before: Aug  1 00:00:00 2020 GMT
            Not After : Aug  1 00:00:00 2024 GMT
examples/puma/client-certs/unknown_ca.crt
        Validity
            Not Before: Aug  1 00:00:00 2020 GMT
            Not After : Aug  1 00:00:00 2024 GMT
examples/puma/client-certs/client_expired.crt
        Validity
            Not Before: Aug  1 00:00:00 2019 GMT
            Not After : Aug  1 00:00:00 2020 GMT
```

After this PR

```shell
~/src/puma renew_test_certs
$ find examples/puma/client-certs -name '*.crt' -print -exec sh -c 'openssl x509 -in {} -noout -text | grep -A2 Validity' \;
examples/puma/client-certs/client.crt
        Validity
            Not Before: Aug  1 00:00:00 2024 GMT
            Not After : Aug  1 00:00:00 2028 GMT
examples/puma/client-certs/ca.crt
        Validity
            Not Before: Aug  1 00:00:00 2024 GMT
            Not After : Aug  1 00:00:00 2028 GMT
examples/puma/client-certs/client_unknown.crt
        Validity
            Not Before: Aug  1 00:00:00 2024 GMT
            Not After : Aug  1 00:00:00 2028 GMT
examples/puma/client-certs/server.crt
        Validity
            Not Before: Aug  1 00:00:00 2024 GMT
            Not After : Aug  1 00:00:00 2028 GMT
examples/puma/client-certs/unknown_ca.crt
        Validity
            Not Before: Aug  1 00:00:00 2024 GMT
            Not After : Aug  1 00:00:00 2028 GMT
examples/puma/client-certs/client_expired.crt
        Validity
            Not Before: Aug  1 00:00:00 2023 GMT
            Not After : Aug  1 00:00:00 2024 GMT
```

**Review by dentarg — APPROVED** [review]

**Comment by tannakartikey** [comment]
Some non-MRI tests for my PR #3438 are still failing. I did not these steps for jRuby. I will confirm and do it.

https://github.com/puma/puma/blob/0e47cace78d9f66f89e2fd432ff86c4660e172f0/examples/puma/client-certs/generate_client_test.rb#L8-L15

**Comment by MSP-Greg** [comment]
@tannakartikey

I've got this down to two failures in the JRuby jobs.  I also added a Ruby file to run all three individual update files.

I'm think about a sh/bash script to do everything...

```text
  1) Failure:
TestPumaServerSSLClient#test_verify_client_cert_with_truststore_without_pass [test/test_puma_server_ssl.rb:480]:
EOFError.
Expected: false
  Actual: true

  2) Failure:
TestPumaServerSSLClient#test_verify_client_cert_with_truststore [test/test_puma_server_ssl.rb:386]:
EOFError.
Expected: false
  Actual: true
```

**Comment by tannakartikey** [comment]
@MSP-Greg 

> I've got this down to two failures in the JRuby jobs. 

Tests are flaky. On my local, sometimes they fail and sometimes they all pass - even without regenerating certs for jRuby (the code snippet I posted earlier). What to do about it? 

I run jRuby tests like this on my local:
```
~/programs/jruby-dist-9.4.8.0-bin/jruby-9.4.8.0/bin/jruby -S bundle exec rake test
```

Is it the correct way? 

-----------
> I also added a Ruby file to run all three individual update files

Great! Looking forward to seeing it.

**Comment by MSP-Greg** [comment]
@tannakartikey

See PR #3442.

Re running tests, I would always set PATH first.  The 'integration' tests run Puma in a sub-process, since the tests may restart the Puma process, stop the Puma process, etc.  That wouldn't work in the test process.

So, if the Ruby you're testing with isn't in PATH, the standard tests that run in the test process will run in the ruby it's running with, but the integration tests will run with the Ruby in your PATH.

Once you have PATH set, you can run the full test suite with `test/runner --verbose` (assuming your in the Puma root folder).  See the [comments](https://raw.githubusercontent.com/puma/puma/master/test/runner) for available options.  A while ago I got tired of typing 'bundle exec rake test *', so we replaced it with `test/runner`...

**Pull request merged**
