### PR TITLE
Add Ruby 3.4 to CI

### PR DESCRIPTION
**Pull request by joshuay03**
Explicitly run CI against Ruby 3.4 now that it's out and [`setup-ruby` has been updated](https://github.com/ruby/setup-ruby/commit/bfefad842bb982ff05b233bcbc1571d97a87e69f).

### CODE REVIEW

**Comment by dentarg** [comment]
Maybe make the switch to Rails 8 for hotwired/turbo-rails in a separate PR? (I don't think what's going on, something about sqlite3 gem: https://github.com/puma/puma/actions/runs/12515093445/job/34912384008#step:6:21)

**Comment by dentarg** [comment]
Probably this that doesn't hold true for Rails 8

https://github.com/puma/puma/blob/339f9cd4a15f643377d8d4b393b83d2985341b9c/.github/workflows/turbo-rails.yml#L54-L55

**Comment by joshuay03** [comment]
> (I don't think what's going on, something about sqlite3 gem: [puma/puma/actions/runs/12515093445/job/34912384008#step:6:21](https://github.com/puma/puma/actions/runs/12515093445/job/34912384008#step:6:21))

Ya the requirement in Rails comes from [here](https://github.com/rails/rails/blob/c31cc0b2e451b9271bdfedc68884e8ae38a7c0fb/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L14), I'll need to figure out where the already installed version is coming from.

**Comment by joshuay03** [comment]
> Probably this that doesn't hold true for Rails 8
> 
> https://github.com/puma/puma/blob/339f9cd4a15f643377d8d4b393b83d2985341b9c/.github/workflows/turbo-rails.yml#L54-L55

Thanks, I've removed it, lets see if it helps.

**Comment by joshuay03** [comment]
Okay, the Rails issue has been resolved. However, it seems like Ruby 3.4 isn't available yet on Windows via `setup-ruby`.

**Comment by dentarg** [comment]
Can you exclude the `windows-2022 3.4` job for now? We want the CI to be green whenever possible.

**Comment by MSP-Greg** [comment]
Commenting it out is fine.  It should be available sometime soon, and Ruby master probably hasn't diverged much from 3.4 yet...

JFYI, almost all GHA Ruby builds are generated by repos in the Ruby organization.  Except the Windows builds...

**Comment by MSP-Greg** [comment]
1. Guess one can't comment out if it's part of the matrix.  Sorry for that.
2. Decided to re-run the one failed job in CI.

Thanks.

**Pull request merged**
