### PR TITLE
Added case when stopping launcher not works

### PR DESCRIPTION
**Pull request by adis-io**
Run this test:
`TESTOPTS="--name test_handler_stops" bundle exec rake test`

P.S. Test fails because it's not implementation, but only test.

### CODE REVIEW

**Comment by adisos** [comment]
@schneems 

Hi, could you please look at this?

**Comment by schneems** [comment]
Is this testing existing functionality, or a filing test for a bug? Master is failing on CI.

**Comment by adisos** [comment]
@schneems 
Filling test for a bug.

**Comment by schneems** [comment]
Thanks, master is failing so a failing CI on a PR isn't unusual right now.

**Comment by nateberkopec** [comment]
The port_open method is incorrect. Replace with the following and everything passes:

screen shot 2017-06-04 at 8 14 39 am

**Comment by nateberkopec** [comment]
[The problem is that binder.close is never called](https://github.com/puma/puma/blob/master/lib/puma/server.rb#L240).

**Comment by evanphx** [comment]
Unsure what this is actually testing...

**Pull request closed without merging**
