### PR TITLE
Support `localhost` integration in `ssl_bind`

### LINKED ISSUE #2708: ssl_bind not compatible with localhost integration
Hi,

I'm really happy that it is now (from v 5.5.0) possible to run Puma with self signed certificates generated by the localhost gem, However, I met a small bump trying to set it up.

I can run self signed SSL from the command line like this:
```puma -b 'ssl://localhost:9292' config.ru```
I would therefore expect one of the following to work in `puma.rb`:
```
ssl_bind 'localhost', '9292'
ssl_bind 'localhost', '9292', {}
```
However this does not work, I have to set it up like this:
```
  ssl_bind 'localhost', '9292', {
    key: "#{ENV["HOME"]}/.localhost/localhost.key",
    cert: "#{ENV["HOME"]}/.localhost/localhost.crt"
  }
```
I found this approach by reading #2706.

I think it would make sense to either support the first version (best in my opinion) or document the second one.

### PR DESCRIPTION
**Pull request by dentarg**
Close #2708
Close #2711

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by dentarg** [comment]
Added missing `skip_if :jruby` to `test_ssl_self_signed_configuration_from_DSL`

**Comment by dentarg** [comment]
[macos-10.15 fail on ruby 2.2](https://github.com/puma/puma/runs/4494217493?check_suite_focus=true#step:4:935) was a strange one though 😕 `Gem::RuntimeRequirementNotMetError: json requires Ruby version >= 2.3.` but it worked on [macos-11 with ruby 2.2](https://github.com/puma/puma/runs/4494217586?check_suite_focus=true#step:4:938) what is going on 🤯

**Comment by MSP-Greg** [comment]
@dentarg Again, working on intermittent CI issues.  macos-10.15 just does weird stuff.  With (yet another) CI patch, I haven't had failures/errors **except** with 10.15...

**Comment by dentarg** [comment]
@MSP-Greg @nateberkopec WDYT?

**Comment by dentarg** [comment]
@nateberkopec could be included in next release?

**Comment by nateberkopec** [comment]
Cheers @dentarg! Thanks for your patience.

**Pull request merged**
