### PR TITLE
Appveyor - Create fat-binary gems and test

### PR DESCRIPTION
**Pull request by MSP-Greg**
Two jobs on Appveyor, 64 bit & 32 bit:
1. Builds Windows fat binary gems - currently for 2.2 thru 2.5. 64 bit also includes trunk.
2. Loops thru all Ruby versions, installs the gem, and tests.
3. Tests are shown on the Appveyor job test tab.
4. Gems and a 7z of test logs are saved as artifacts.
5. Current commit info (date, short SHA, summary) is stored in gemspec as metadata.
6. Shared Powershell files are downloaded from Appveyor.  Only three files added to repo.

Built three times on my [fork](https://ci.appveyor.com/project/MSP-Greg/puma/history), builds 10-12. Approx time is 11 minutes.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@nateberkopec @schneems @evanphx

If any of you have the time to read it and reply, I've added an issue at the repo containing the shared code for the topic of Windows pre-compiled gems and testing on Appveyor.

https://github.com/MSP-Greg/av-gem-build-test/issues/1

Thanks, Greg

**Comment by schneems** [comment]
Both CI's are failing.

**Comment by MSP-Greg** [comment]
@schneems

See https://ci.appveyor.com/project/MSP-Greg/puma,  just ran a moment ago, passed all except trunk-x64-JIT.

Re Travis, see #1620

The Appveyor failure here is due to the old gnupg package on Appveyor, as mentioned in #1621.  This PR uses script/PowerShell file contained in another repo, so it's more complete code.

One benefit of that is that sometime I will change trunk-x64 to OpenSSL 1.1.1, and when I do, I don't need to make any changes here.

Reminder - this has a commit that is similar to #1616, so I may need to remove the code here...

Thanks, Greg

**Comment by MSP-Greg** [comment]
Just rebased.  Issues with MSYS2 gnupg fixed after some time with `pacman -Qi` and `pactree`.  Hence, and as it should be, all packages used with Ruby 2.4 forward are checked for signatures.

FYI, Trunk 64 bit JIT has been passing...

**Comment by MSP-Greg** [comment]
Re trunk JIT, Appveyor on my [fork](https://ci.appveyor.com/project/MSP-Greg/puma/build/job/k6g1k97ls95srp9s/messages) took 106 sec, this [ci](https://ci.appveyor.com/project/puma/puma/build/1.0.114/job/xj729xdia5cmfoi7/messages) took 185 sec.  To see a test summary click on 'Test Summary 64 bit'.  Most of the other new Ruby versions take approx. 34 sec.

But, Appveyor jobs run on two cores.  Running on a quad locally, the JIT build took 34 secs.

Just in case you were wondering...

**Comment by MSP-Greg** [comment]
Just built again on my fork.  Results at https://ci.appveyor.com/project/MSP-Greg/puma/build/32

Passed.

Also, trunk-x64 is passing with OpenSSL 1.1.1 (built today from master) with essentially one test change.

**Comment by MSP-Greg** [comment]
We all know Travis & Appveyor have a lot of items needing updates.  Just the fact that all Ruby versions on Travis Ubuntu are using OpenSSL 1.0.1 says a lot.

The build system used for Windows Ruby is MSYS2/MinGW.  It also gets outdated on Appveyor, but if one performs a new install of Ruby (>= 2.4), the default prompts will update your local build system.  Also, MSYS2/MinGW doesn't really support incremental updates.  There are quite a few packages on Appveyor, so a full update can take anywhere from six to 12 minutes.  Given normal test architecture, that would be per job, or for each version of Ruby tested.  Lastly, the current gcc release is 8.2.0, but Appveyor only has 7.3.0.

So, what should be used for Appveyor testing?  Updated or existing Appveyor?

Secondly, there's the issue of OpenSSL.  Right or wrong, Windows Ruby 2.5 is built with 1.1.0.  But, the standard MSYS2/MinGW OpenSSL package is still at 1.0.2, due to the shear number of packages built with it (including Git for Windows).  Ruby trunk is currently testing with 1.1.1.

Due to these two issues, and the fact that compiling is required for both testing and constructing a Windows pre-compiled gem, I created the code included here.

It relies on code outside of this repo, but that is the code that efficiently handles updating the Appveyor build system, selecting the correct OpenSSL package, compiling, constructing the gem, and testing.  Since it only requires two build jobs, it runs faster than the traditional setup.

This has sat for a while, and other PR's connected with unstable testing have done the same.  Is there anything we can do to help?

**Pull request closed without merging**
