### PR TITLE
File.open -> File.read, File.write [changelog skip]

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description
File.open creates an IO object, which may appear when looking at 'leftover' IO objects.

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` or `[ci skip]` to the pull request title.
- [ ] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by cjlarose** [comment]
> which may appear when looking at 'leftover' IO objects.

may appear to what? The garbage collector? The test suite?

**Comment by MSP-Greg** [comment]
Sorry, I was wondering about phrasing that.  We want Puma and the test suite to cleanup io objects, normally one would check with `ObjectSpace` methods...

**Comment by cjlarose** [comment]
Okay. Well these changes seem harmless, but maybe not necessary.

If you're trying to ensure that the test suite closes file descriptors cleanly, scanning `ObjectSpace` for instances of `IO` is a good start, but IO instances that represent already-closed file descriptors seem harmless (they just haven't been GC'd yet). Really, it seems like it'd be sufficient to ensure that `ObjectSpace.each_object(IO).all?(:closed?)`

**Comment by MSP-Greg** [comment]
> it'd be sufficient to ensure that ObjectSpace.each_object(IO).all?(:closed?)

It was a while ago, but I was checking the test suite for issues with IO objects, as there were tests that didn't clean up.  Haven't done so recently.  Don't recall whether the test suite uses any...

**Comment by MSP-Greg** [comment]
@cjlarose

> but maybe not necessary

It was Windows related, and I can't recall the specifics, but sometime in the past I've had issues with `File.open`.   Windows treats files with open handles differently than *nix systems.

Granted, most production systems using Puma are not Windows, but I suspect there are some people 'learning' Ruby & Rails on Windows...

**Comment by nateberkopec** [comment]
Similarly skeptical about any correctness improvement here, but I do think this makes things a little bit cleaner so I think we should merge.

**Pull request merged**
