### PR TITLE
Fix 3 corner cases when request body is chunked

### PR DESCRIPTION
**Pull request by florin555**
I have found and fixed 3 cases when puma does not read a chunked body correctly.

In the first case it hangs.

In the second and third cases it adds extra bytes to the body.

Please see the individual commit messages for more information.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Hi, Florian, cool changes!

I went and read the AppVeyor failed-build output.

This is the output message from the failed AppVeyor build: does it tell you anything?

```
  1) Error:
TestPumaServer#test_chunked_request_pause_between_cr_lf_after_size_of_second_chunk:
Errno::ECONNABORTED: An established connection was aborted by the software in your host machine.
    C:/projects/puma/test/test_puma_server.rb:686:in `read'
    C:/projects/puma/test/test_puma_server.rb:686:in `test_chunked_request_pause_between_cr_lf_after_size_of_second_chunk'
```

<details>

```
TestPumaServer#test_chunked_request_pause_between_cr_lf_after_size_of_second_chunk = [MinitestRetry] retry 'test_chunked_request_pause_between_cr_lf_after_size_of_second_chunk' count: 1,  msg: Errno::ECONNABORTED: An established connection was aborted by the software in your host machine.
    C:/projects/puma/test/test_puma_server.rb:686:in `read'
    C:/projects/puma/test/test_puma_server.rb:686:in `test_chunked_request_pause_between_cr_lf_after_size_of_second_chunk'
[MinitestRetry] retry 'test_chunked_request_pause_between_cr_lf_after_size_of_second_chunk' count: 2,  msg: Errno::ECONNABORTED: An established connection was aborted by the software in your host machine.
    C:/projects/puma/test/test_puma_server.rb:686:in `read'
    C:/projects/puma/test/test_puma_server.rb:686:in `test_chunked_request_pause_between_cr_lf_after_size_of_second_chunk'
[MinitestRetry] retry 'test_chunked_request_pause_between_cr_lf_after_size_of_second_chunk' count: 3,  msg: Errno::ECONNABORTED: An established connection was aborted by the software in your host machine.
    C:/projects/puma/test/test_puma_server.rb:686:in `read'
    C:/projects/puma/test/test_puma_server.rb:686:in `test_chunked_request_pause_between_cr_lf_after_size_of_second_chunk'
2.05 s = E
```

</details>

**Comment by florin555** [comment]
Hi! Thanks for the feedback.

I made some exploratory commits and I was able to isolate the source of the problem to the fact that in that particular test I used 2 sleeps and wrote to the socket 2 times. All other tests sleep and write to the socket at most once.

Otherwise the test follows the same pattern like all the other tests.

I was not able to reproduce the failure on my computer, and also Travis CI is passing, so I believe it must be something specific to Appveyor, but I don't have a way to debug further.

The test needs the 2 sleeps because the bug that the test tries to reproduce happens only in that case, so I can't just change the test because then it becomes meaningless.

**Comment by olleolleolle** [comment]
@florin555 _Perhaps_ you know how to make a focused query to https://help.appveyor.com/discussions/problems ?

**Comment by nateberkopec** [comment]
Is this related to #1480?

**Comment by florin555** [comment]
https://github.com/puma/puma/issues/1480 is different. This pull request fixes other issues.

**Comment by mubashirhanif** [comment]
@florin555 and I think that the failing test is because of a potential bug in ruby on windows.

```
# https://github.com/preisanalytics/puma/blob/382cdaf2cdbb781f91d7e0ee8a36c6d8b4c88c66/lib/puma/client.rb#L203
def read_chunked_body
      ...
        rescue Errno::EAGAIN
          return false
        rescue SystemCallError, IOError
          raise ConnectionError, "Connection error detected during read"
        end
      ...
end
```
On Linux and Mac the exception `Errno::EWOULDBLOCK` is just an alias to `Errno::EAGAIN`.
On windows, these exceptions point to 2 different objects/exceptions, which causes the code to raise a wrong exception instead of returning false(the expected behaviour).

Also note `[Errno::EAGAIN::Errno, Errno::EWOULDBLOCK::Errno]` outputs
`[11, 11]` on linux, `[35, 35]` on Mac and `[11, 10035]` on windows(verified on 1.9.3 and 2.3.3). 

In this ruby-doc it says that both `Errno::EWOULDBLOCK` and `Errno::EAGAIN` are extended by `IO::WaitReadable`(verified on both Windows and Linux). And also since 1.9.3 is support is dropped by Puma. So I think we ca we can safely replace `Errno::EAGAIN` and `Errno::EWOULDBLOCK` with `IO::WaitReadable` in case of exception from `IO::read_nonblock` method.

**Comment by mubashirhanif** [comment]
The current failing builds on Travis are inherited from the current state of master branch.

**Comment by florin555** [comment]
@olleolleolle, @nateberkopec could you please merge this, now that the build is green?

**Comment by pschrammel** [comment]
hi, sorry pushing: Are there any merge blockers? How can this go upstream?

**Pull request merged**
