### PR TITLE
Test timeout gets [changelog skip]

### PR DESCRIPTION
**Pull request by nateberkopec**
Discovered this working locally and wondering why my tests were hanging.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Good idea.

> Discovered this working locally

Had the same problem.

> `def wait_until_server_logs(server, msg)`

Maybe something like `def wait_until_server_logs(msg, server: @server)`?

I guess I like kwargs for optional parameters...

I'm working on this issue in a branch, incorporating the ideas of the 'setup_puma' concept (https://github.com/puma/puma/issues/1971).

The issue with needing a pid, (and hence, another process) to test signalling leaves one without much info if something crashes.  I changed to using spawn, grabbing stderr, which (sometimes) has info re the crash.  Also fixes an issue on Windows (and maybe other OS's?) when using `Kernel.exec` in the 'other' process.

Adding a method like this makes it easier to throw all the output to the console, and if it times out, check the stderr output...

**Comment by nateberkopec** [comment]
The failure for Windows on 2.5/2.6 is really weird: https://github.com/puma/puma/pull/1990/checks?check_run_id=241355633#step:9:104

**Comment by MSP-Greg** [comment]
My equivalent to `wait_until_server_logs` (`wait_server`) uses `IO.select` instead of `Timeout.timeout`, which is Ruby and adds another thread.  It also has a `debug:` kwarg, which dumps everything read/gotten to STDOUT as it's looking for the match.

It seems to be working well, and JFYI, when I changed `parallelize_me!` so that it was disabled for JRuby in a few files, JRuby CI became a lot more stable and even passes sometimes.

In general, we've got parallel testing, which adds a thread, `TimeoutEveryTestCase` adds another thread, etc, etc.  Given that many of the JRuby CI logs show a lot of 'waiting on join' kinds of timeouts,  I figured switching to `IO.select` might be helpful.  It may even be possible to eliminate `TimeoutEveryTestCase`...

> The failure for Windows on 2.5/2.6 is really weird

I think Windows Ruby 2.4 is skipped.  I've got all versions passing in my 'enhanced test framework'...

**Comment by MSP-Greg** [comment]
@nateberkopec

Here's the code I was using.  I added quite a bit for string/regex, debugging, etc.
```ruby
def wait_server(re, server: @server, debug: false, timeout: 10)
  regex = Regexp === re ? re : Regexp.new(Regexp.escape re)
  STDOUT.puts('',
    "#{' ' * 20}*** #{full_name} wait_server #{re} ***") if debug
  l = ''

  while IO.select([server], nil, nil, timeout) do
    l = server.gets
    STDOUT.puts "#{l}" if debug
    break if l[regex]
  end
  # TODO add debugging output to use server STDERR if available
  assert l[regex], "Server timeout waiting for '#{re}' in:\n    #{caller(1..2)}"
  l
end
```

Re the TODO comment, I switched to spawn from IO.popen, so stderr is available, but often doesn't have any helpful info.

**Comment by nateberkopec** [comment]
Thanks for the code. Windows 2.5./2.6 still failing on `TestLauncher#test_dependencies_and_files_to_require_after_prune_is_correctly_built_with_extra_deps = 0.01 s = .
^CThe process tried to write to a nonexistent pipe.`

I think this is coming from the Plugin test class.

**Comment by nateberkopec** [comment]
Hm. Still failing on https://github.com/puma/puma/pull/1990/checks?check_run_id=246697262#step:9:75

**Comment by MSP-Greg** [comment]
I think :INT below needs to change to :KILL or Windows may have issues:

https://github.com/puma/puma/blob/60d2ab5898eb0ab7a38d2f0b4b9c920fd5f90312/test/helpers/integration.rb#L23-L26

Also, I know I revised the below, something like `#{caller(1..2).join "\n    "}`, and I may have changed the indexes (four spaces after \n)...
```ruby
assert l[regex], "Server timeout waiting for '#{re}' in:\n    #{caller(1..2)}"
```

**Pull request closed without merging**
