### PR TITLE
EOL Rubies are not supported by `rack-conform`.

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Review by dentarg — APPROVED** [review]

**Comment by dentarg** [comment]
Do we know why the 3.1 build fails?

**Comment by MSP-Greg** [comment]
I added a line to the setup-ruby step that updates RubyGems/Bundler.  rack-conform did pass, but turbo-rails failed.  Maybe we can add mintest-retry to it?  Not today...

**Comment by dentarg** [comment]
Closed by https://github.com/puma/puma/pull/3416

**Comment by MSP-Greg** [comment]
Sorry, I spaced on this, I just saw the failure in another PR...

**Comment by ioquatix** [comment]
It's all good as long as it's fixed :)

**Pull request closed without merging**
