### PR TITLE
Actions: two workflows, MRI & non MRI, separate README badges [changelog skip]

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

Currently two Actions workflows exist, one for with SSL, another without SSL.  Note that these could be combined.

But, non MRI jobs are often failing, and we all hate red badges.  Also, things like Actions step timeouts, etc may vary between MRI and non-MRI jobs.

PR creates two new workflows that separate jobs into MRI and non-MRI.  Adjust README badges as such.

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` or `[ci skip]` to the pull request title.
- [ ] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by dentarg** [comment]
I wonder if there's another phrase to use instead of "non MRI" (I can't think of one right now). This came up because I noticed that the filtering over at https://github.com/puma/puma/actions?query=workflow%3AMRI does not work as expected, "MRI" catches both. Oh well :)

**Comment by MSP-Greg** [comment]
That's why I changed the links.  Let me see if a non-breaking space works...

**Comment by cjlarose** [comment]
Is there any value in keeping JRuby and TruffleRuby in the same action? Seems like we'd avoid the name "non MRI" by splitting them.

I guess then we'd get more red X's that way, but at least it'd still be easy to tell if MRI tests are passing or not.

**Comment by MSP-Greg** [comment]
I used 'non_MRI', and filtering etc works.  Non-breaking space did not.

**Pull request merged**
