### PR TITLE
Add after_refork hook

### PR DESCRIPTION
**Pull request by Drakula2k**
### Description
Adds `after_refork` hook to be able to re-create the resources that were removed in `on_refork` on the worker 0 (Mongo connections in my use case).

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by johnnyshields** [comment]
@nateberkopec the use case for `after_refork`  is:

- We use `before_refork` to disconnect any active database sockets on worker0
- We use `on_worker_boot` to reconnect database/restart monitoring threads on the grandchild instance
- However, there is **currently no way to reconnect on worker0**; it stays disconnected even after forking.

Note that `after_refork` triggers only on worker0 and not on the grandchilds; the grandchilds will use `on_worker_boot` as normal.

**Comment by johnnyshields** [comment]
@nateberkopec can you please take a look at this?

**Comment by johnnyshields** [comment]
We've been using this branch in prod for ~3 months with no issue--it completely fixed the problem we were seeing.

**Comment by johnnyshields** [comment]
@nateberkopec @dentarg may we ask to get this reviewed and merged?

**Comment by Drakula2k** [comment]
@johnnyshields the button is accessible to me, done it, the build still passes

**Comment by nateberkopec** [comment]
Thanks for your patience 🙇

**Pull request merged**
