### PR TITLE
Avoid mutating global STDOUT & STDERR

### PR DESCRIPTION
**Pull request by montanalow**
The current behavior prevents apps from benefitting from `STDOUT.sync = false` during configuration phases, since the initial call to `Event.stdio` is relatively late in the boot cycle.

### CODE REVIEW

**Comment by nateberkopec** [comment]
I'm afraid I don't understand the use case.

This PR mostly changes how our internal logs interact with flush. This seems weird, first of all, because the whole point of `sync = false` is, IMO, to let Ruby do the `flush`ing for you.

I also don't understand the PR title - how was global stdout and stderr being modified before this PR?

**Comment by montanalow** [comment]
`$stdout = STDOUT` by default.

This call results in setting `$stdout.sync = true`. 
https://github.com/puma/puma/blob/master/lib/puma/events.rb#L149

In the current code path, whenever `Puma::Events.stdio` is called, `STDOUT` & `STDERR` will be changed to `sync`. `sync` is not the default behavior for `STDOUT` & `STDERR` so this is a side effect on a global variable that will have application wide results.

I would like to prevent this side effect, so Puma applications can run with `STDOUT.sync # => false` 

I'm unfamiliar with the reasoning behind the current code setting `sync = true`, but my patch preserves the behavior of synchronized output for `Events`, by flushing `stdout` and `stderr` any time output is written.

**Comment by nateberkopec** [comment]
Why not just change the default IO to a new STDOUT/STDERR object, then?

E.g. 

```ruby
def self.stdio
    Events.new $stdout.dup, $stderr.dup
end
```

**Comment by nateberkopec** [comment]
That leaves the separate issue of us forcing you to use sync = false, but at least we avoid the global side effect.

**Comment by nateberkopec** [comment]
Actually, even better:

```ruby 
def self.stdio 
    stdout = $stdout.dup
    stdout.sync = false 
    stderr = $stderr.dup 
    stderr.sync = false
    Events.new stdout, stderr
end

then rm the sync code from Events#initialize 
```

**Comment by montanalow** [comment]
@nateberkopec To catch `DEFAULT = new(STDOUT, STDERR)` as well, I moved the dup inside initialize, which I think aligns with your suggestions.

**Comment by nateberkopec** [comment]
I think that's OK, but you'll need to make sure that [the rack handler](https://github.com/puma/puma/blob/master/lib/rack/handler/puma.rb#L69) changes it's arguments so that the correct item is used.

**Comment by montanalow** [comment]
Not sure I follow, are you worried about the resulting `StringIO.new.dup` from `Rack::Events.strings`?

**Comment by nateberkopec** [comment]
On that line, `::Puma::Events.stdio` (which is the code path we'll take if the the silent option is NOT present) will return the global stdout/stderr. That is then passed into Puma::Launcher#new, avoiding the change that you've made here b/c the event is passed in explicitly.

**Comment by montanalow** [comment]
Sorry if I'm still missing something, but I thought that's what my change would address. By `dup`ing the args from all callers inside `Events#intitialize`, before `sync` is set, there shouldn't be any way to get update the globals, even if you pass them in.

`Events.stdio` will be `dup`ped, so won't impact `$stdout`, and `Events::DEFAULT` will also be `dup`ped to avoid mutating STDOUT, when called from `Puma::Launcher#initialize` here https://github.com/puma/puma/blob/master/lib/puma/launcher.rb#L48

**Comment by nateberkopec** [comment]
Well, write a test and we'll find out then 😆 You'll have to fix the tests that are looking for output at $stdout/$stderr too unfortunately.

**Comment by nateberkopec** [comment]
Looking at this again and I think you're probably write, but it does need new tests + fixes of the old ones for a merge.

**Comment by nateberkopec** [comment]
Thanks for all your work @montanalow !

**Comment by nateberkopec** [comment]
Who could have guessed the entire Puma logging ecosystem somehow depended on us modifying STDOUT.sync to true... a good lesson for software maintainership - modifying a global is probably worth a major version bump!

**Pull request merged**
