### PR TITLE
fix jruby deleting env vars

### PR DESCRIPTION
**Pull request by grosser**
@nateberkopec

### CODE REVIEW

**Comment by grosser** [comment]
hmm no I think this is even worse ... setting to "" will prevent things like Dotenv to load new env vars ... I'll have another look maybe just skip for now since it keeps the old behavior ...

**Comment by nateberkopec** [comment]
That's annoying :( [It looks like it *should* work, maybe we should make a report.](https://github.com/jruby/jruby/blob/f7746d0be94f5d9f7cd27af610f1bc5dd2622794/spec/ruby/core/env/replace_spec.rb#L10)

**Comment by grosser** [comment]
updated with a safer fixup ... better semi-broken then completely broken ...
otherwise we'd set `""` everywhere and things sure would break ...
also once jruby is fixed it will just work ...

**Comment by grosser** [comment]
basically it will behave as before without this fix ... so not a degradation/blocker ... and once jruby is fixed it will work just fine

**Comment by nateberkopec** [comment]
Works for me. I love how all the stars aligned and we didnt see any ioerrors on the CRuby parts of this built.

**Comment by grosser** [comment]
tried reproducing it but without success ... so there must be something weird going on :/

```
ruby -e 'ENV["FOO"] = "BAR"; ENV.replace({}); exec "ruby -e \"puts ENV[%{FOO}]\""'
```

**Pull request merged**
