### PR TITLE
Update turbo-rails.yml

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

When the turbo-rails workflow was added, it was rather 'hacky'.  After trying a better way with the rack-conform workflow, returned to the turbo-rails file...

Modify Gemfile to use Puma from Repo & SHA generating workflow, misc changes.

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by nateberkopec** [comment]
Is that a meaningful fail? I can't tell 🤔

**Comment by MSP-Greg** [comment]
> Is that a meaningful fail? I can't tell

Not sure myself.  It seems like it's either a GitHub network issue or an edge case with Actions caching.  The failure was with `bundle install`, or, it didn't even get to testing.  The error shown:
```
  Revision 768c413f01dbcc2e7a7ca787eec07cf00b638b98 does not exist in the
  repository https://github.com/puma/puma.git. Maybe you misspelled it?
  If this error persists you could try removing the cache directory
```

But, https://github.com/puma/puma/commit/768c413f01dbcc2e7a7ca787eec07cf00b638b98 is valid...

**Comment by MSP-Greg** [comment]
My fork passed, by another failure here with Ruby 3.1.  Going to force a bundler update in setup-ruby, and see if that fixes the issue.

**Comment by MSP-Greg** [comment]
Just rebased...

All the turbo-rails jobs passed both [here](https://github.com/puma/puma/actions/runs/4070278393) and in my [fork](https://github.com/MSP-Greg/puma/actions/runs/4070278070).

All the test jobs passed except 'NON-MRI: macos-11 truffleruby' in my fork.

**Pull request merged**
