### PR TITLE
Fix timing out requests too early

### LINKED ISSUE #2574: Timeout during long file upload
**Not really a bug, more clarification**

We use a little file upload server that is a simple rack application and uses Puma as the server. I upgraded it from 4.3.3 to 5.2.2 and now we see timeouts after 30 seconds (`first_data_timeout`) when uploading files to it where the upload takes longer than 30 seconds. I can increase `first_data_timeout` and the timeout happens at the appropriate time.

An example using curl of an upload is pretty simple `curl --data-binary @file.zip server:5000/upload?some=params`

The application runs in our Kubernetes cluster behind Traefik which sits behind an AWS ALB/WAF. All that doesn't seem to matter though as using port-forward to talk directly to the pod gives the same result.

Looking in some code it looks like `first_data_timeout` is deprecated in v6? Or is that just the `attr_writer` for it?

Just wanting some guidance as to what I should be looking at to solve this problem. I could just revert back to 4.3.3 (which I'll probably do for now), but I'd like to keep upgrading and running the newer version for security, performance, etc., reasons.

I'm slightly confused as to why it's happening in the first place, since I don't know where the data is buffering for it to be waiting and causing puma to timeout. Or is the name `first_data_timeout` just not accurate in this case and it is getting data, but it's timing out for another reason?

Do I need some other puma configuration? Should I be running nginx in a sidebar to sit in front of puma?

**Puma config**

```
workers 1
threads 1, 16

preload_app!

rackup      DefaultRackup
port        5000
environment 'production'
```

### PR DESCRIPTION
**Pull request by wjordan**
### Description

Fixes #2574 (a regression released in v5.0.3), with an added test to prevent future regressions.

#### See also

#2575 extends this fix by adding a `between_bytes_timeout` configuration option that allows for different timeout values for the initial data received by the client, and subsequent chunks of data. This extra option may eventually be useful but this PR is intended to more narrowly fix the regression first.

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@wjordan 

LGTM.  Maybe change `test_timeout_in_data_phase` (line 385 in the PR) to the following?  Using `1.1` worked locally, added 0.05 for CI:
```ruby
def test_timeout_in_data_phase
  @server.first_data_timeout = 1
  server_run

  sock = send_http "POST / HTTP/1.1\r\nHost: test.com\r\nContent-Type: text/plain\r\nContent-Length: 5\r\n\r\n"
  sleep 1.15
  sock << "Hello"

  data = sock.gets

  assert_equal "HTTP/1.1 408 Request Timeout\r\n", data
end
```

**Comment by MSP-Greg** [comment]
@wjordan

So the 'Windows' guy (me) now does 95% of his Puma work with WSL2/Ubuntu20.04.  Sorry for that.

Not sure what I think of the 'Errno::ECONNABORTED' being raised so quickly, what's your opinion?

**Comment by MSP-Greg** [comment]
I saw you setting the timing to zero, I'm running the following in my fork right now...
```ruby
def test_timeout_in_data_phase
  @server.first_data_timeout = 1
  server_run

  sock = send_http "POST / HTTP/1.1\r\nHost: test.com\r\nContent-Type: text/plain\r\nContent-Length: 5\r\n\r\n"
  sleep 1.15
  sock << "Hello"

  if Puma::IS_WINDOWS
    assert_raises(Errno::ECONNABORTED) { sock.gets }
  else
    data = sock.gets
    assert_equal "HTTP/1.1 408 Request Timeout\r\n", data
  end
end
```

**Comment by MSP-Greg** [comment]
Looks like both versions are passing.  I also had a nonrelated failure...

**Comment by MSP-Greg** [comment]
I made the change with `assert_raises` since it was the `gets` that was causing the failure, not the `<<`/`write`.

**Comment by wjordan** [comment]
It looks like a Windows `TCPSocket` raises `ECONNABORTED` on the next read, if a socket is written to after being closed at the other end- so skipping the write if the response is already returned (`unless IO.select()`) seems to work and still tests to make sure the timeout is sent in time.

**Comment by MSP-Greg** [comment]
> tests to make sure the timeout is sent in time.

Works for me.

**Pull request merged**
