### PR TITLE
[2440] Better byebug integration

### LINKED ISSUE #2440: Better byebug integration
[Cluster-mode Puma and byebug (default gem in Rails) play poorly together.](https://stackoverflow.com/questions/40998929/puma-rails-5-binding-pry-only-available-for-60-seconds-before-timeout)

Not sure what a good course of action is here.

### PR DESCRIPTION
**Pull request by juanmanuelramallo**
# Description
Proposal to solve #2440

I tested it locally with a Rails app and it worked as expected. So if this approach is in the right path, I'd need pointers on how to write tests for it.

I haven't added an entry to the HISTORY.md file because I don't know if this is correct. I'd like to first verify that. 

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` or `[ci skip]` to the pull request title.
- [ ] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

Closes #2440

### CODE REVIEW

**Comment by juanmanuelramallo** [comment]
Hey @nateberkopec, is this something similar to what you had in mind?

**Comment by nateberkopec** [comment]
I'm not sure this will work. Many people may be (accidentally, true) deployed into a "development" environment, so this PR makes me nervous.

**Comment by nateberkopec** [comment]
I think you may have misread my comment on #2440. I meant maybe we should open a PR _to Rails_ (the default puma config, I mean), and increase worker_timeout in dev mode there.

Certainly as written, this change would have to wait until 6.0.

What do you think?

**Comment by juanmanuelramallo** [comment]
Fair enough! 
Yep it makes total sense to actually update the default puma config from Rails itself rather than doing it here. 

Closing the PR then.

**Pull request closed without merging**
