### PR TITLE
fix #1214 Puma >= 3.6.1 + SSL + Persistent Connections. Puma Hangs :(

### LINKED ISSUE #1214: Puma >= 3.6.1 + SSL + Persistent Connections. Puma Hangs :(
Since we've upgraded to puma 3.7.0 from 3.6.0 we started to experience a very annoying issue in development. Puma would hang sometimes.

After an intense Friday afternoon we've managed to pin-point the problem.

### Steps to reproduce

1) Run any basic rack app using puma greater than or equal to 3.6.1. With the approriate configuration to run in SSL mode: puma -b 'ssl://0.0.0.0:3000?cert=/path/to/cert/localhost.crt&key=/path/to/key/localhost.key'

2) Request a page from an IRB session using a library with persistent connections like Typhoeus: Typhoeus.get('https://localhost:3000')

3) Press CTRL+C on puma process, puma says: "Gracefully stopping, waiting for requests to finish" but it never stops

4) Run the request again from the IRB console: Typhoeus.get('https://localhost:3000')

5) Puma unstuck itself

I wonder if it has been caused by this commit: https://github.com/puma/puma/commit/df18d9331dd9c07f76859e2605dbfb88e71fd92d 
just because it mentions SSL and it's in 3.6.1 tag.

I hope it helps.

### PR DESCRIPTION
**Pull request by respire**
#1214 
master one

### CODE REVIEW

**Comment by etscrivner** [comment]
Can confirm that this is an issue, and has been blocking an upgrade for some time.

**Comment by evanphx** [comment]
I'm not sure how this fixes it, you appear to have removed the code that runs the data through the SSL engine.

**Comment by evanphx** [comment]
Oh, nevermind. `readnonblock` is running it through as expected.

**Comment by vincentwoo** [comment]
would really love a new version cut with this fix! Puma is hard to use in dev with SSL currently.

**Comment by vincentwoo** [comment]
Hi @evanphx, sorry to nag, but I really think it'd be great to get a new Puma version out with this fix.

**Comment by nateberkopec** [comment]
Release is blocked on #1344

**Comment by vincentwoo** [comment]
Is there any chance we can get a release cut without #1344? This one seems quite serious in comparison.

**Comment by nateberkopec** [comment]
No. I'm not going to release something I know is broken. You can use master branch.

**Pull request merged**
