### PR TITLE
Support decryption of SSL key

### LINKED ISSUE #3132: Support the ability to decrypt SSL key
**Is your feature request related to a problem? Please describe.**

We have customers that are required to encrypt SSL keys and other secrets at rest. Currently `key` is a plaintext file. 

Other Web servers implement this in a number of ways:

1. NGINX supports an `ssl_password_file` (https://www.nginx.com/blog/secure-distribution-ssl-private-keys-nginx/). The file can contain multiple passwords separated by newlines, and NGINX attempts to decrypt the SSL private key with each passphrase in the file. 
2. Apache supports the ability to execute a script via the `SSLPassPhraseDialog` option (https://www.oreilly.com/library/view/apache-the-definitive/0596002033/re177.html). This script prints the password to `stdout`.

**Describe the solution you'd like**

The first solution would suffice, though the second seems more elegant. https://www.nginx.com/blog/protecting-ssl-private-keys-nginx-hashicorp-vault/ demonstrates how you could use a background process to populate a FIFO special file.

### PR DESCRIPTION
**Pull request by stanhu**
This pull request makes it possible to store an encrypted SSL key on disk and have Puma decrypt it at runtime by supplying a `key_password_command`. Supplying a `key_password_command` will cause Puma to:

1. Execute the external program.
2. Read the password from stdout and remove the trailing newline.
2. Configure the OpenSSL callbacks to use the password.

Other Web servers, such as NGINX and Apache, have a similar feature.
NGINX only allows supplying a password file via the `ssl_password`
parameter (https://www.nginx.com/blog/secure-distribution-ssl-private-keys-nginx/),
while Apache has a `SSLPassPhraseDialog` option (https://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslpassphrasedialog) that allows an admin to execute an external program.

Closes #3132

### Description
Please describe your pull request. Thank you for contributing! You're the best.

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@stanhu

Thank you for the PR.  Good idea.

Re the Windows tests, I think they'll run and pass with the changes at https://github.com/MSP-Greg/puma/commit/096b970f01 (or the [patch](https://github.com/MSP-Greg/puma/commit/096b970f01.patch)).

**Comment by stanhu** [comment]
@MSP-Greg Thanks for the quick review and patch! Could you take a look now?

**Review by MSP-Greg — APPROVED** [review]

**Comment by nateberkopec** [comment]
Great work @stanhu 👍

**Comment by stanhu** [comment]
@nateberkopec Sure thing! When is the next Puma release slated to go out?

**Comment by nateberkopec** [comment]
Probably 2 weeks

**Pull request merged**
