### PR TITLE
Backport set CONTENT_LENGTH for chunked requests

### PR DESCRIPTION
**Pull request by TheRusskiy**
### Description
Backporting https://github.com/puma/puma/pull/2287 to 4.3 version

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` or `[ci skip]` to the pull request title.
- [x] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

Tests passed locally for me.
> 268 runs, 658 assertions, 0 failures, 0 errors, 2 skips

Rubocop shows a warning for this line, not related to this PR:
https://github.com/TheRusskiy/puma/blob/f3b409c565d67557c04ad37c10a42dd8cad0b655/lib/puma/server.rb#L697

### CODE REVIEW

**Comment by nateberkopec** [comment]
Neat! I'll take a look, we might be able to release this next week along with 5.1.

Appreciate you taking the time to follow up and backport this for everyone 🙏

**Comment by nateberkopec** [comment]
A new 4.3.x release should be out today with this change

**Comment by TheRusskiy** [comment]
Nate the neat!

**Comment by nateberkopec** [comment]
Released as 4.3.7

**Pull request merged**
