### PR TITLE
warn when bundler fails and avoid having to use -I to run tests

### PR DESCRIPTION
**Pull request by grosser**

### CODE REVIEW

**Comment by grosser** [comment]
@nateberkopec this looking good ?

**Comment by nateberkopec** [comment]
Sorry, what I meant was that the entire `require test_helper` line should remain the same. There's no reason to use require_relative here.

**Comment by grosser** [comment]
The reason I changed that is to allow `ruby test/test_foo.rb` to work

**Comment by grosser** [comment]
... that might not be an issue for senior devs, but it's not obvious that you have to add the magic `-Itest` incantation

**Comment by nateberkopec** [comment]
Fair enough

**Pull request merged**
