### PR TITLE
Replace usages of "MRI" with "CRuby"

### PR DESCRIPTION
**Pull request by cjlarose**
### Description

Most places in the codebase and in the docs that reference "MRI" are actually talking about CRuby. For a discussion about the difference, this blog post is useful: https://engineering.appfolio.com/appfolio-engineering/2017/12/28/cruby-mri-jruby-rubyspec-rubinius-yarv-a-little-bit-of-ruby-naming

### Your checklist for this pull request

- [X] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [X] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [X] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [X] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [X] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [X] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by nateberkopec** [comment]
Personally I'm in favor, but I've received mixed feedback in the past about this nomenclature on Twitter. FWIW even Koichi Sasada thinks we should call it MRI, even though he basically completely replaced MRI with YARV.

**Comment by MSP-Greg** [comment]
I don't have a strong opinion either way, but Takashi Kokubun in a [blog](https://medium.com/@k0kubun/ruby-3-0-jit-and-beyond-4d9404ce33c) dated Dec 25, 2020 said 'Ruby 3.0 JIT is the fastest JIT ever for MRI' in the first line.  Or, I'm not sure there is consensus on this...

**Comment by nateberkopec** [comment]
https://twitter.com/nateberkopec/status/1376565712060260353

**Comment by cjlarose** [comment]
Haha I guess I thought this was more-or-less settled since Matz' preference was to use CRuby, but it looks like at least according to your poll that most folks still think of it as MRI.

**Comment by dentarg** [comment]
@nateberkopec you did ask what people thought it is called, not what their preference are. New poll with more context?

(I've talked to two people who guessed MRI but then said they prefer CRuby.)

**Comment by cjlarose** [comment]
I don't feel too strongly about this. MRI seems more universal, even if the historical definition of "MRI" isn't consistent with how it's used today. But language changes over time, and that's cool.

**Pull request closed without merging**
