### PR TITLE
[ci skip] Add link to a community plugin

### PR DESCRIPTION
**Pull request by amrrbakry**
### Description
Please describe your pull request. Thank you for contributing! You're the best.

Add a link to another community plugin

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by nateberkopec** [comment]
Thanks @amrrbakry !

**Comment by nateberkopec** [comment]
@dentarg @MSP-Greg did we change/mess up the [ci skip] check? This contributor added it to the PR title as per our instructions, but the tests still ran. We should either change our check, or change the instructions.

**Comment by amrrbakry** [comment]
> @dentarg @MSP-Greg did we change/mess up the [ci skip] check? This contributor added it to the PR title as per our instructions, but the tests still ran. We should either change our check, or change the instructions.

@nateberkopec It's my mistake. I added too late, after creating the PR.

**Comment by dentarg** [comment]
You can also include that phrase in the commit message. That's built into GitHub

**Comment by dentarg** [comment]
Something we as maintainers ought to remember to do when we squash merge doc fixes

**Comment by nateberkopec** [comment]
>That's built into GitHub

TIL

**Pull request merged**
