### PR TITLE
do not blow up when RUBYOPT is not defined

### PR DESCRIPTION
**Pull request by grosser**
tried to run from master ... kaboom :D

```
NoMethodError: undefined method `include?' for nil:NilClass
  puma-0d7a8bb5f377/lib/puma/launcher.rb:171:in `run'
```

### CODE REVIEW

**Comment by grosser** [comment]
@nateberkopec

**Comment by stereobooster** [comment]
I suppose this PR shadows this one https://github.com/puma/puma/pull/1348/files.

**Comment by grosser** [comment]
kinda ... was not sure what that did in addition to this "just fix it"
change ... so I made a new PR

**Comment by nateberkopec** [comment]
Yeah, this looks like it does the same thing as #1348 with a much smaller change.

@grosser why don't we .dup ORIGINAL_ENV

**Comment by grosser** [comment]
added .dup for good measure ... might have produced weird errors if someone shells our from a puma process

**Pull request merged**
