### PR TITLE
CI: Add Ruby 3.1

### PR DESCRIPTION
**Pull request by dentarg**
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

### CODE REVIEW

**Comment by dentarg** [comment]
Hmm, some race condition now?

https://github.com/puma/puma/runs/4674154365?check_suite_focus=true#step:3:159 the `load ruby` step failed on `bundle install`

```
bundle install
  /opt/hostedtoolcache/Ruby/2.5.9/x64/bin/bundle config --local path /home/runner/work/puma/puma/vendor/bundle
  Your RubyGems version (2.7.6.3)) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
  /opt/hostedtoolcache/Ruby/2.5.9/x64/bin/bundle lock
  Your RubyGems version (2.7.6.3)) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
  Fetching gem metadata from https://rubygems.org/.........
  Resolving dependencies...
  Writing lockfile to /home/runner/work/puma/puma/Gemfile.lock
  Cache key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.5.9-Gemfile.lock-58401606124bcf0b08bb60fcb483029668ae5c955dfdb96abbc522d68ecf38bd
  Received 9354437 of 9354437 (100.0%), 53.1 MBs/sec
  Cache Size: ~9 MB (9354437 B)
  /usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/74557641-8f8f-4a51-93a1-b854f8d1beb2/cache.tzst -P -C /home/runner/work/puma/puma
  Cache restored successfully
  Found cache for key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.5.9-Gemfile.lock-6de2272664299eef6905e55e5bf3f81c10c3bdd480cddcbbee32e8b9ae0a7266
  /opt/hostedtoolcache/Ruby/2.5.9/x64/bin/bundle install --jobs 4
  Your RubyGems version (2.7.6.3)) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
  Failed to load /home/runner/.gemrc, wrong number of arguments (given 2, expected 1)
  Fetching gem metadata from https://rubygems.org/........
  Using rake 13.0.6
  Using bundler 2.3.4
  Using jaro_winkler 1.5.4
  Using ast 2.4.2
  Using json 2.6.1
  Using localhost 1.1.9
  Using method_source 1.0.0
  Using minitest 5.15.0
  Using minitest-stub-const 0.6
  Using nio4r 2.5.8
  Using parallel 1.21.0
  Using powerpack 0.1.3
  Using stringio 3.0.1
  Using rack 2.2.3
  Using rainbow 3.0.0
  Using rake-compiler 1.1.6
  Using ruby-progressbar 1.11.0
  Fetching unicode-display_width 1.4.1
  Using sd_notify 0.1.1
  Using m 1.6.0
  Using minitest-retry 0.2.2
  Using minitest-proveit 1.0.0
  Using parser 3.0.3.2
  Using puma 5.5.2 from source at `.` and installing its executables
  Using psych 4.0.3
  Using rdoc 6.4.0
  --- ERROR REPORT TEMPLATE -------------------------------------------------------
  

  ArgumentError: wrong number of arguments (given 4, expected 1)
    /home/runner/work/puma/puma/vendor/bundle/ruby/2.5.0/gems/psych-4.0.3/lib/psych.rb:323:in `safe_load'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/safe_yaml.rb:31:in `safe_load'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package.rb:496:in `block (2 levels) in read_checksums'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package.rb:495:in `wrap'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package.rb:495:in `block in read_checksums'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package/tar_reader.rb:116:in `seek'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package.rb:494:in `read_checksums'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package.rb:547:in `block (2 levels) in verify'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package/tar_reader.rb:29:in `new'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package.rb:546:in `block in verify'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package/file_source.rb:30:in `open'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package/file_source.rb:30:in `with_read_io'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package.rb:545:in `verify'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/package.rb:526:in `spec'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/rubygems_integration.rb:221:in `spec_from_gem'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/source/rubygems.rb:167:in `install'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:54:in `install'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/worker.rb:62:in `apply_func'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/worker.rb:57:in `block in process_queue'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/worker.rb:54:in `loop'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/worker.rb:54:in `process_queue'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/bundler-2.3.4/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'
  ```

but at https://github.com/puma/puma/runs/4674145733?check_suite_focus=true#step:3:137 the same job (Ubuntu 20.04, Ruby 2.5) worked 😒

**Comment by dentarg** [comment]
@MSP-Greg maybe `setup-ruby-pkgs` ought to update rubygems before `bundle install` is run?

Now done in the workflow afterwards to address certain things:

https://github.com/puma/puma/blob/d676c659e7de20aa1c1f78b43d1f1f0c33cddf1a/.github/workflows/mri.yml#L55-L67

**Comment by MSP-Greg** [comment]
@dentarg

Working on it.

**Comment by MSP-Greg** [comment]
This PR points out what I believe is an issue with Actions workflows.  Two cases:

1. I have a fork of the origin repo, and am working on a PR.  I want to run Actions in my fork, using the branch that I would use for the PR to the origin repo.
2. A maintainer/owner creates a branch in the origin repo, using it for a PR.  This PR is that case.

AFAIK, there is no way to allow the first to work without the second running workflows in both the branch and the PR.

**Comment by MSP-Greg** [comment]
**Off-topic:**  The workflow here is using my fork of setup-ruby.  The branch used is open in a PR in setup-ruby, but there hasn't been time to discuss, etc.

So, at some point, setup-ruby will work with all the changes (Actions MSYS2 changes, Windows ucrt, RubygGems & Bundler, etc).  When that occurs, I may no longer support the branch (`MSP-Greg/ruby-setup-ruby/win-ucrt-1`) being used here...

**Comment by MSP-Greg** [comment]
@dentarg All yours. Happy New Year to all…

**Comment by nateberkopec** [comment]
Thanks to both of y'all - happy 2022!

**Pull request merged**
