### PR TITLE
[CI] test_puma_server.rb - update & add tests for back-to-back requests

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

Add a 'pipeline' test using chunked request bodies, misc updates to helper functions

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by dentarg** [comment]
Looks like this needs at least a rebase

**Comment by MSP-Greg** [comment]
> Looks like this needs at least a rebase

Yes.  This coder also needs more coffee.

Since I've decided to work from a branch that contains all the test updates, then cherry picking into separate PRs, I have a lot of rebasing as those PR's are merged.  Also wanting to delete the branches used for the cherry picked PRs as they are merged, otherwise I have a lot of confusing stale branches in my fork.

I think that made sense...

**Comment by MSP-Greg** [comment]
I rebased and revised the code as needed.

Current code uses `test_immediate_pipeline_` as a prefix for these tests.  I changed it to `test_back_to_back`.

'Pipeline' often is used to refer to server behavior, where a server is guaranteed to send responses in the same order as back-to-back requests.  This isn't an issue with Puma, but depending on front end use/configuration, it could be.  Anyway, I can revert the test name change.

**Review by dentarg — APPROVED** [review]

**Comment by MSP-Greg** [comment]
@dentarg

Thanks.  I'm adding more back-to-back requests to other tests also.  I hope the 'back-to-back' phrase makes sense.  The phrase 'pipelined' is also used, but that often refers to a server that will always send the responses in the same order as the requests.

Currently, since there's a one-to-one mapping between client objects and accepted sockets, and a client processes requests in the order received, Puma does handle pipelined requests...

**Pull request merged**
