### PR TITLE
support full certificate chain PEM for `cert_pem:` parameter to `ssl_bind`

### LINKED ISSUE #3172: Inconsistency between cert: and cert_pem: parameters to ssl_bind
## Describe the bug
When using `ssl_bind` the documentation seems to indicate that the following are equivalent:

**File based certs/keys** 

https://github.com/puma/puma/blob/763d1a1a971d9bb17fc1478859d626a539c29970/lib/puma/dsl.rb#L513-L520

**String based certs/keys**
https://github.com/puma/puma/blob/763d1a1a971d9bb17fc1478859d626a539c29970/lib/puma/dsl.rb#L526-L531

This appears to be incorrect.

When `cert:` is passed to `ssl_bind` - inside MiniSSL this file is loaded from disk using [`SSL_CTX_use_certificate_chain_file()`](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_use_certificate_chain_file.html)
> SSL_CTX_use_certificate_chain_file() loads a certificate chain from file into ctx. The certificates must be in PEM format and must be sorted starting with the subject's certificate (actual client or server certificate), followed by intermediate CA certificates if applicable, and ending at the highest level (root) CA

https://github.com/puma/puma/blob/763d1a1a971d9bb17fc1478859d626a539c29970/ext/puma_http11/mini_ssl.c#L272-L278

When `cert_pem:` is passed to `ssl_bind` - inside MiniSSL this file is loaded using a combination of [`PEM_read_bio_X509`](https://www.openssl.org/docs/man1.0.2/man3/PEM_read_bio_X509.html) and [`SSL_CTX_use_certificate`](https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_use_certificate.html)

https://github.com/puma/puma/blob/763d1a1a971d9bb17fc1478859d626a539c29970/ext/puma_http11/mini_ssl.c#L300-L311

If the contents of the file at `path_to_cert` is a full chain PEM then:

- passing `cert: path_to_cert` a fully resolve cert chain is served up by puma
- passing in `cert_pem: File.read(path_to_cert)` results in **only** the certificate itelf being loaded, and not the full chain.

## To Reproduce

Take the self contained gist [`puma_ssl_test.rb`](https://gist.github.com/copiousfreetime/8ad7784ea609b2c5f6e5a3ccf0c9a2d6) and run it with ruby:

```
curl -s -O https://gist.githubusercontent.com/copiousfreetime/8ad7784ea609b2c5f6e5a3ccf0c9a2d6/raw/4c0197fafbf24fe2bf10438e873752b60e44c4ed/puma_ssl_test.rb 
ruby puma_ssl_test.rb --help
```

There are 3 different tests

1. `ruby puma_ssl_test.rb --test files` 
2. `ruby puma_ssl_test.rb --test strings`
3. `ruby puma_ssl_test.rb --test ca`

## Expected Behavior

I would expect that give the same contents to `cert_pem:` that was in the file that was given to `cert:` should result in the same level of ssl validation.

**`ruby puma_ssl_test.rb --test files`** 
```
% ruby puma_ssl_test.rb --test files
Writing pem/cert.pem
Writing pem/key.pem
Writing pem/ca.pem
Writing pem/all.pem
Test puma with ssl_bind options:

  cert: pem/all.pem
  key: pem/key.pem

The cert file contains the certificate and the entire cert chain


Once Puma is running, you can test it with:

echo | openssl s_client -host anchor.lcl.host -port 9292 -debug -servername anchor.lcl.host | grep 'O=anchordotdev'

Puma starting in single mode...
* Puma version: 6.2.2 (ruby 3.2.2-p53) ("Speaking of Now")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 171
* Listening on ssl://[::]:9292?cert=pem%2Fall.pem&key=pem%2Fkey.pem&verify_mode=none
Use Ctrl-C to stop
```

And testing the ssl

```
% echo | openssl s_client -host anchor.lcl.host -port 9292 -debug -servername anchor.lcl.host | grep 'O=anchordotdev'
depth=2 O = anchordotdev, CN = development - AnchorCA
verify error:num=19:self signed certificate in certificate chain
verify return:0
DONE
 0 s:/O=anchordotdev/CN=anchor.lcl.host
   i:/O=anchordotdev/CN=anchor - SubCA
 1 s:/O=anchordotdev/CN=anchor - SubCA
   i:/O=anchordotdev/CN=development - AnchorCA
 2 s:/O=anchordotdev/CN=development - AnchorCA
   i:/O=anchordotdev/CN=development - AnchorCA
subject=/O=anchordotdev/CN=anchor.lcl.host
```

What I would expect -- full cert chain and notification that the self signed cert is there.

**`ruby puma_ssl_test.rb --test strings`** 

```
% ruby puma_ssl_test.rb --test strings
Test puma with ssl_bind options:

  cert_pem: contents of pem/all.pem
  key_pem: contents of pem/key.pem

The cert_pem option contains the certificate and the entire cert chain


Once Puma is running, you can test it with:

echo | openssl s_client -host anchor.lcl.host -port 9292 -debug -servername anchor.lcl.host | grep 'O=anchordotdev'

Puma starting in single mode...
* Puma version: 6.2.2 (ruby 3.2.2-p53) ("Speaking of Now")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 263
* Listening on ssl://[::]:9292?cert=store%3A0&key=store%3A1&verify_mode=none
Use Ctrl-C to stop
```

And testing the ssl

```
% echo | openssl s_client -host anchor.lcl.host -port 9292 -debug -servername anchor.lcl.host | grep 'O=anchordotdev'
depth=0 O = anchordotdev, CN = anchor.lcl.host
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 O = anchordotdev, CN = anchor.lcl.host
verify error:num=21:unable to verify the first certificate
verify return:1
DONE
 0 s:/O=anchordotdev/CN=anchor.lcl.host
   i:/O=anchordotdev/CN=anchor - SubCA
subject=/O=anchordotdev/CN=anchor.lcl.host
issuer=/O=anchordotdev/CN=anchor - SubCA
```

The cert chain is missing.

## Observations

It appears that in order to use the `cert_pem:` option and get the same results as using `cert:` you **must** also use the `ca:` and `verify_mode:` options

**`ruby puma_ssl_test.rb --test ca`**
```
% ruby puma_ssl_test.rb --test ca
Test puma with ssl_bind options:

  cert_pem: contents of pem/cert.pem
  key_pem: contents of pem/key.pem
  ca: pem/ca.pem
  verify_mode: peer

The cert_pem option contains only the certificate.
The ca option is the path to the rest of the cert chain


Once Puma is running, you can test it with:

echo | openssl s_client -host anchor.lcl.host -port 9292 -debug -servername anchor.lcl.host | grep 'O=anchordotdev'

Puma starting in single mode...
* Puma version: 6.2.2 (ruby 3.2.2-p53) ("Speaking of Now")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 379
* Listening on ssl://[::]:9292?cert=store%3A0&key=store%3A1&verify_mode=peer&ca=pem%2Fca.pem
Use Ctrl-C to stop
``` 

And testing results in the same result as using `cert:` with the path to a file

```
% echo | openssl s_client -host anchor.lcl.host -port 9292 -debug -servername anchor.lcl.host | grep 'O=anchordotdev'
depth=2 O = anchordotdev, CN = development - AnchorCA
verify error:num=19:self signed certificate in certificate chain
verify return:0
DONE
 0 s:/O=anchordotdev/CN=anchor.lcl.host
   i:/O=anchordotdev/CN=anchor - SubCA
 1 s:/O=anchordotdev/CN=anchor - SubCA
   i:/O=anchordotdev/CN=development - AnchorCA
 2 s:/O=anchordotdev/CN=development - AnchorCA
   i:/O=anchordotdev/CN=development - AnchorCA
subject=/O=anchordotdev/CN=anchor.lcl.host
issuer=/O=anchordotdev/CN=anchor - SubCA
```
## Questions

- Is this the expected behavior when using `cert_pem:` 
- Or is it the `cert:` option that is actually out of spec, and they should both be using `ca:` 
- Should there also be a `ca_pem:` option for passing a string based ca option so none of them need to read from disk?
- Should we submit a PR that attempts to resolve this and get consistent behavior, or is this something that you are readily familiar enough that would be trivial to resolve for you?

## Desktop Environment (please complete the following information)

- OS: macOS Monterey - 12.6.4
- Puma Version  Puma version: 6.2.2 (ruby 3.2.2-p53) ("Speaking of Now")

### PR DESCRIPTION
**Pull request by copiousfreetime**
### Description

Bring the `cert_pem:` parameter into parity with the `cert:` parameter to `ssl_bind`.

Currently the `cert:` parameter allows for a full certificate chain file to be used, and the `cert_pem:` only allows a certificate. This patch allows the `cert_pem:` parameter to be be a full certificate chain String.

See #3172 for an in depth discussion of the issue.

Closes #3172 

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature. 
  - **I need guidance on how to add a test for this**
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@copiousfreetime

Thanks for working on this.  Not sure if you've thought about tests.  I've got two commits on https://github.com/MSP-Greg/puma/commits/00-3174, I believe they add what's needed.  Thoughts?

**Comment by MSP-Greg** [comment]
Re the effect of this PR, after cherry-picking the two last commits (which only have test changes) onto master, then running `test_puma_server_ssl.rb`, the following error occurs:
```
  1) Failure:
TestPumaSSLCertChain#test_chain_cert_string_without_ca [/puma/test/test_puma_server_ssl.rb:583]:
--- expected
+++ actual
@@ -1 +1 @@
-["anchor.lcl.host", "SubCA", "AnchorCA"]
+["anchor.lcl.host"]
```

**Comment by copiousfreetime** [comment]
Thanks for those tests! That's the result I was looking for. And that's what I would expect on master, that's what I was seeing when doing the commandline testing.

One thing we probably want to do is use different certs. Those anchor from my example are set to expire in 1 year, so probably not good for test data. We'll have some unexpected test failures next June - which will make everyone unhappy. 

I'll take a look at getting better test data, or generating it.

**Comment by MSP-Greg** [comment]
Glad those helped.  I didn't want to assume that an openssl exe was in PATH, so I used Ruby SSLSockets.

I like to point out the failures/errors in master, helps when one has totally forgotten what change/feature the PR adds.

> Those anchor from my example are set to expire in 1 year

Glad you remembered that, I didn't look.

> I'll take a look at getting better test data, or generating it.

Thanks.  If you could, adding the code to generate them in the comments/notes is helpful.

**Comment by copiousfreetime** [comment]
@MSP-Greg I think we're all good - added [`generate_chain_test.rb`](examples/puma/chain_cert/generate_chain_test.rb) and brought all the naming conventions in line with the `client_certs` directory. This does add the [`certificate_authority`](https://rubygems.org/gems/certificate_authority) gem as development dependency for help in generating the intermediate signing cert. That gem might be useful elsewhere for development too.

I also added[`test_example_cert_expiration.rb`](test/test_example_cert_expiration.rb) that checks the expiration dates of all the certs in the repo that I could find. So we should get a 30 day notice from CI if the certs are about to expire.

This test did find that the certs in [examples/CA](https://github.com/puma/puma/tree/master/examples/CA) all expired a while ago. And I wasn't able to find if they are actually used for something. This might be a cleanup for another PR, but thought I would mention it here.

**Comment by dentarg** [comment]
> This does add the [`certificate_authority`](https://rubygems.org/gems/certificate_authority) gem as development dependency for help in generating the intermediate signing cert. That gem might be useful elsewhere for development too.

If we only use that gem in `generate_chain_test.rb` we can do an [inline gemfile](https://bundler.io/guides/bundler_in_a_single_file_ruby_script.html) in that script instead of adding it to the general Gemfile. It is an awesome and probably underused feature of Bundler :)

**Comment by copiousfreetime** [comment]
> > This does add the [`certificate_authority`](https://rubygems.org/gems/certificate_authority) gem as development dependency for help in generating the intermediate signing cert. That gem might be useful elsewhere for development too.
> 
> If we only use that gem in `generate_chain_test.rb` we can do an [inline gemfile](https://bundler.io/guides/bundler_in_a_single_file_ruby_script.html) in that script instead of adding it to the general Gemfile. It is an awesome and probably underused feature of Bundler :)

Good call - I'll make that change - I use inline bundler all the time.

**Review by nateberkopec — APPROVED** [review]

**Comment by MSP-Greg** [comment]
@nateberkopec

A few days ago I added a 'feature' label.  Now, I'm not sure if it should be 'feature' or 'bug'.  I'm now thinking it should be 'bug'.

Currently, when using `DSL#ssl_bind`, the following two code lines should be equivalent if the cert file contains multiple certs, but they are not, as `cert_pem` fails:
```ruby
cert_pem: path_to_cert
cert_pem: File.read(path_to_cert)
```
This PR aligns the functionality of the two.

Thoughts?

**Pull request merged**
