### PR TITLE
Refactor response writes, test refactors, fix UNPACK_TCP_STATE_FROM_TCP_INFO location

### LINKED ISSUE #2556: Undefined constant on platforms without tcp_cork support  and with closed_socket support
Missing constant `Read: #<NameError: uninitialized constant Puma::Server::UNPACK_TCP_STATE_FROM_TCP_INFO>` on platforms that have no 'tcp_cork_support?' and do have 'closed_socket_supported?'

https://stackoverflow.com/questions/66088219/pumaserverunpack-tcp-state-from-tcp-info/66214024#66214024

In file `lib/puma/server.rb`  is the following construct:

```ruby 
    if tcp_cork_supported?
      UNPACK_TCP_STATE_FROM_TCP_INFO = "C".freeze
      # ...
    end 
 
    if closed_socket_supported?
     # ... 
      state = tcp_info.unpack(UNPACK_TCP_STATE_FROM_TCP_INFO)[0]
    end
```

If tcp_cork_supported? is FALSE  and closed_socket_supported? is TRUE, an uninitialized constant Puma::Server::UNPACK_TCP_STATE_FROM_TCP_INFO is used! 

Is it a problem to move  'UNPACK_TCP_STATE_FROM_TCP_INFO = "C".freeze' outside the if condition?

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

1. **request.rb**
  1.1. Refactor `handle_request`
  1.2. Refactor and simplify `fast_write` for fewer string assignments

2. **minissl.rb**
  2.1. Refactor and simplify `write` for fewer string assignments

3. **server.rb**
  3.1 Move `UNPACK_TCP_STATE_FROM_TCP_INFO` to correct location
  3.2. Add `PURGE_INTERRUPT_QUEUE` constant
  3.3. Refactor `cork_socket`, `uncork_socket`, & `closed_socket?` to work with ssl sockets
  3.4. Return from above before entering begin block
  3.5 Anchor Ruby 'root' constants, e.g. `Socket` and `TCPSocket`

4. **test_puma_server.rb**
  4.1 Add multi-byte characters to `test_very_large_return`
  4.2 Cleanup `@server.stop` code, misc

5. **test_puma_server_ssl.rb**
  5.1. Add multi-byte characters to `test_very_large_return`
  5.2. Rename a few variables, quotes, misc

#### NOTES:

Code refactors done while working on updated test framework.

CI using updated tests - [MRI](https://github.com/MSP-Greg/puma/actions/runs/567077651), [non-MRI](https://github.com/MSP-Greg/puma/actions/runs/567077654).  At the bottom of the test step log, see 'Debugging Info`, and click open to see various integration test info.

Closes #2556

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` or `[ci skip]` to the pull request title.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Also added a fix for check_changelog.yml, missing a paren...

**Comment by dentarg** [comment]
> Also added a fix for check_changelog.yml, missing a paren...

Oops, my bad (26776c86dfdef24372b43ba3dab213754334a4f7), however, I think you could add that paren directly to master :)

**Comment by MSP-Greg** [comment]
Rebased

**Comment by MSP-Greg** [comment]
Closing in favor of #2595.  I will extract test updates and maybe a few lib updates (3.3, 3.4, ??) from this into another pr...

**Pull request closed without merging**
