### PR TITLE
Fix warning of ILLEGAL_HEADER_KEY_REGEX

### PR DESCRIPTION
**Pull request by JuanitoFatas**
### Description

Fixes a warning in test coming from `ILLEGAL_HEADER_KEY_REGEX`. [Square bracket](https://thepugautomatic.com/2012/09/brackets-in-regular-expressions/) may not match what we wanted.

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` or `[ci skip]` to the pull request title.
- [ ] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by nateberkopec** [comment]
Thanks Juanito!

**Comment by MSP-Greg** [comment]
@nateberkopec @JuanitoFatas 

Apologies, I saw this open then close, then reopen, and should have commented.

Original:
```ruby
[\u0000-\u0025|#{DQUOTE}|#{HTTP_HEADER_DELIMITER}]
```
The first segment `\u0000-\u0025` is a character class, so two options, I think:
```ruby
[\u0000-\u0025#{DQUOTE}#{HTTP_HEADER_DELIMITER}]
or
([\u0000-\u0025]|#{DQUOTE}|#{HTTP_HEADER_DELIMITER})
```
But, I think that still has an overlap, possible due to octal/decimal mixup.

Note that `("\u0020".."\u0025").to_a.join` is equal to ` !"#$%`  (space character at the beginning), so the overlap is the doubel quote.  I'm not sure about the other characters, whether they're acceptable...

**Comment by nateberkopec** [comment]
Actually backslash overlaps as well

**Comment by nateberkopec** [comment]
I guess the real fix here is to remove the overlaps.

**Comment by MSP-Greg** [comment]
I noticed and the next step was finding/reviewing the spec, at which point I said 'later'.

> I guess the real fix here is to remove the overlaps.

I'm not sure what 'printable' characters are allowed...

**Pull request merged**
