### PR TITLE
Load JSON at runtime

### LINKED ISSUE #2206: Regression in 4.3.3 with require json
**Describe the bug**
Hello, https://github.com/puma/puma/pull/1801 introduced a regression in 4.3.3 when using puma with prune_bundler and control-app if you issue a phased restart with an app with a different json gem version you end up with the following error :

```
/home/ylecuyer/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:312:in `check_for_activated_spec!': You have already activated json 2.3.0, but your Gemfile requires json 2.1.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```
**Puma config:**

```ruby
# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
#
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
#
port        ENV.fetch("PORT") { 3000 }

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked web server processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
# workers ENV.fetch("WEB_CONCURRENCY") { 2 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory.
#
# preload_app!

prune_bundler

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```

This is the default rails new template for config/puma.rb I have only added prune_bundler

**To Reproduce**

https://youtu.be/6VYPTLrFKIg

```
rails new puma-json
cd puma-json
bundle exec puma -p 6000 -w 4 --control-url 'tcp://127.0.0.1:9293' --control-token foo
```

Edit Gemfile and add:

```
gem 'json', '2.1.0'
```

Send phased restart signal to puma

**Expected behavior**

Workers should restart successfully no matter the json version used in the app.

### PR DESCRIPTION
**Pull request by MSP-Greg**
### Description

Fixes loading JSON when Gemfile contains JSON versions that differ from the default gem or previously loaded versions.  Various versions of Bundler have had issues with default gems, as it also loads some for them.

This PR changes JSON loading to runtime.

Closes #2206

### Your checklist for this pull request
- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added an entry to [History.md](../blob/master/History.md) if this PR fixes a bug or adds a feature. If it doesn't need an entry to HISTORY.md, I have added `[changelog skip]` the pull request title.
- [ ] I have added appropriate tests if this PR fixes a bug or adds a feature.
- [x] My pull request is 100 lines added/removed or less so that it can be easily reviewed.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed, including Rubocop.

### CODE REVIEW

**Comment by ylecuyer** [comment]
It is working with my reproduction example ;)

I have mixed feelings about this PR as it fixes the issue but isn't really future proof

**Comment by MSP-Greg** [comment]
> but isn't really future proof

In what sense?  Loading/requiring at runtime is essentially the same as autoload.

**Comment by ylecuyer** [comment]
What I meant was if someone in a future commit adds a `require 'json'` on top of a new file we won't notice it until it breaks again

**Comment by MSP-Greg** [comment]
Given the possible issues with default gems, I think it would be worthwhile to autoload json, psych/yaml, and openssl.  Using autoload removes the need for adding multiple requires when loading at runtime.

I'll have a look at all three.

**Comment by nateberkopec** [comment]
I'm gonna roll with this for now, we can do a longterm fix later.

**Pull request merged**
